import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // public/welcome-design/* is the approved landing design served byte-for-byte
  // (vendored + generated by scripts/build-welcome-transplant.mjs). Don't lint/
  // reformat it — that would fight the verbatim transplant and be overwritten on
  // the next build.
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "public/welcome-design/**",
      "design/**",
      "unconventional-signup-flow-design/**",
      // Claude Design handoff bundle (reference only, never committed into the
      // app). Same posture as the other vendored design dirs above.
      "uniplug-dashbaord/**",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
