/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentSignupRouteImport } from './routes/student-signup'
import { Route as MentorSignupRouteImport } from './routes/mentor-signup'
import { Route as IndexRouteImport } from './routes/index'

const StudentSignupRoute = StudentSignupRouteImport.update({
  id: '/student-signup',
  path: '/student-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorSignupRoute = MentorSignupRouteImport.update({
  id: '/mentor-signup',
  path: '/mentor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mentor-signup': typeof MentorSignupRoute
  '/student-signup': typeof StudentSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mentor-signup': typeof MentorSignupRoute
  '/student-signup': typeof StudentSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mentor-signup': typeof MentorSignupRoute
  '/student-signup': typeof StudentSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mentor-signup' | '/student-signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mentor-signup' | '/student-signup'
  id: '__root__' | '/' | '/mentor-signup' | '/student-signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MentorSignupRoute: typeof MentorSignupRoute
  StudentSignupRoute: typeof StudentSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-signup': {
      id: '/student-signup'
      path: '/student-signup'
      fullPath: '/student-signup'
      preLoaderRoute: typeof StudentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-signup': {
      id: '/mentor-signup'
      path: '/mentor-signup'
      fullPath: '/mentor-signup'
      preLoaderRoute: typeof MentorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MentorSignupRoute: MentorSignupRoute,
  StudentSignupRoute: StudentSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
