/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudentSignupRouteImport } from './routes/student-signup'
import { Route as SessionNotesRouteImport } from './routes/session-notes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MentorTermsRouteImport } from './routes/mentor-terms'
import { Route as MentorSignupRouteImport } from './routes/mentor-signup'
import { Route as MentorDashboardRouteImport } from './routes/mentor-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionNotesNoteIdRouteImport } from './routes/session-notes.$noteId'
import { Route as ParentalConsentTokenRouteImport } from './routes/parental-consent.$token'
import { Route as MessagesConversationIdRouteImport } from './routes/messages_.$conversationId'
import { Route as MentorIdRouteImport } from './routes/mentor.$id'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicHooksSendEventEmailRouteImport } from './routes/api/public/hooks/send-event-email'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSignupRoute = StudentSignupRouteImport.update({
  id: '/student-signup',
  path: '/student-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionNotesRoute = SessionNotesRouteImport.update({
  id: '/session-notes',
  path: '/session-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorTermsRoute = MentorTermsRouteImport.update({
  id: '/mentor-terms',
  path: '/mentor-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorSignupRoute = MentorSignupRouteImport.update({
  id: '/mentor-signup',
  path: '/mentor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorDashboardRoute = MentorDashboardRouteImport.update({
  id: '/mentor-dashboard',
  path: '/mentor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionNotesNoteIdRoute = SessionNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => SessionNotesRoute,
} as any)
const ParentalConsentTokenRoute = ParentalConsentTokenRouteImport.update({
  id: '/parental-consent/$token',
  path: '/parental-consent/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages_/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorIdRoute = MentorIdRouteImport.update({
  id: '/mentor/$id',
  path: '/mentor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendEventEmailRoute =
  ApiPublicHooksSendEventEmailRouteImport.update({
    id: '/api/public/hooks/send-event-email',
    path: '/api/public/hooks/send-event-email',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/mentor-dashboard': typeof MentorDashboardRoute
  '/mentor-signup': typeof MentorSignupRoute
  '/mentor-terms': typeof MentorTermsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-notes': typeof SessionNotesRouteWithChildren
  '/student-signup': typeof StudentSignupRoute
  '/terms': typeof TermsRoute
  '/mentor/$id': typeof MentorIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/parental-consent/$token': typeof ParentalConsentTokenRoute
  '/session-notes/$noteId': typeof SessionNotesNoteIdRoute
  '/api/public/hooks/send-event-email': typeof ApiPublicHooksSendEventEmailRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/mentor-dashboard': typeof MentorDashboardRoute
  '/mentor-signup': typeof MentorSignupRoute
  '/mentor-terms': typeof MentorTermsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-notes': typeof SessionNotesRouteWithChildren
  '/student-signup': typeof StudentSignupRoute
  '/terms': typeof TermsRoute
  '/mentor/$id': typeof MentorIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/parental-consent/$token': typeof ParentalConsentTokenRoute
  '/session-notes/$noteId': typeof SessionNotesNoteIdRoute
  '/api/public/hooks/send-event-email': typeof ApiPublicHooksSendEventEmailRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/mentor-dashboard': typeof MentorDashboardRoute
  '/mentor-signup': typeof MentorSignupRoute
  '/mentor-terms': typeof MentorTermsRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-notes': typeof SessionNotesRouteWithChildren
  '/student-signup': typeof StudentSignupRoute
  '/terms': typeof TermsRoute
  '/mentor/$id': typeof MentorIdRoute
  '/messages_/$conversationId': typeof MessagesConversationIdRoute
  '/parental-consent/$token': typeof ParentalConsentTokenRoute
  '/session-notes/$noteId': typeof SessionNotesNoteIdRoute
  '/api/public/hooks/send-event-email': typeof ApiPublicHooksSendEventEmailRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/community-guidelines'
    | '/cookie-policy'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/mentor-dashboard'
    | '/mentor-signup'
    | '/mentor-terms'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/progress'
    | '/refund-policy'
    | '/reset-password'
    | '/session-notes'
    | '/student-signup'
    | '/terms'
    | '/mentor/$id'
    | '/messages/$conversationId'
    | '/parental-consent/$token'
    | '/session-notes/$noteId'
    | '/api/public/hooks/send-event-email'
    | '/api/public/hooks/send-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/community-guidelines'
    | '/cookie-policy'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/mentor-dashboard'
    | '/mentor-signup'
    | '/mentor-terms'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/progress'
    | '/refund-policy'
    | '/reset-password'
    | '/session-notes'
    | '/student-signup'
    | '/terms'
    | '/mentor/$id'
    | '/messages/$conversationId'
    | '/parental-consent/$token'
    | '/session-notes/$noteId'
    | '/api/public/hooks/send-event-email'
    | '/api/public/hooks/send-reminders'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/browse'
    | '/community-guidelines'
    | '/cookie-policy'
    | '/dashboard'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/mentor-dashboard'
    | '/mentor-signup'
    | '/mentor-terms'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/progress'
    | '/refund-policy'
    | '/reset-password'
    | '/session-notes'
    | '/student-signup'
    | '/terms'
    | '/mentor/$id'
    | '/messages_/$conversationId'
    | '/parental-consent/$token'
    | '/session-notes/$noteId'
    | '/api/public/hooks/send-event-email'
    | '/api/public/hooks/send-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MentorDashboardRoute: typeof MentorDashboardRoute
  MentorSignupRoute: typeof MentorSignupRoute
  MentorTermsRoute: typeof MentorTermsRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionNotesRoute: typeof SessionNotesRouteWithChildren
  StudentSignupRoute: typeof StudentSignupRoute
  TermsRoute: typeof TermsRoute
  MentorIdRoute: typeof MentorIdRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  ParentalConsentTokenRoute: typeof ParentalConsentTokenRoute
  ApiPublicHooksSendEventEmailRoute: typeof ApiPublicHooksSendEventEmailRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-signup': {
      id: '/student-signup'
      path: '/student-signup'
      fullPath: '/student-signup'
      preLoaderRoute: typeof StudentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-notes': {
      id: '/session-notes'
      path: '/session-notes'
      fullPath: '/session-notes'
      preLoaderRoute: typeof SessionNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-terms': {
      id: '/mentor-terms'
      path: '/mentor-terms'
      fullPath: '/mentor-terms'
      preLoaderRoute: typeof MentorTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-signup': {
      id: '/mentor-signup'
      path: '/mentor-signup'
      fullPath: '/mentor-signup'
      preLoaderRoute: typeof MentorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-dashboard': {
      id: '/mentor-dashboard'
      path: '/mentor-dashboard'
      fullPath: '/mentor-dashboard'
      preLoaderRoute: typeof MentorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-notes/$noteId': {
      id: '/session-notes/$noteId'
      path: '/$noteId'
      fullPath: '/session-notes/$noteId'
      preLoaderRoute: typeof SessionNotesNoteIdRouteImport
      parentRoute: typeof SessionNotesRoute
    }
    '/parental-consent/$token': {
      id: '/parental-consent/$token'
      path: '/parental-consent/$token'
      fullPath: '/parental-consent/$token'
      preLoaderRoute: typeof ParentalConsentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages_/$conversationId': {
      id: '/messages_/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/$id': {
      id: '/mentor/$id'
      path: '/mentor/$id'
      fullPath: '/mentor/$id'
      preLoaderRoute: typeof MentorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-event-email': {
      id: '/api/public/hooks/send-event-email'
      path: '/api/public/hooks/send-event-email'
      fullPath: '/api/public/hooks/send-event-email'
      preLoaderRoute: typeof ApiPublicHooksSendEventEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SessionNotesRouteChildren {
  SessionNotesNoteIdRoute: typeof SessionNotesNoteIdRoute
}

const SessionNotesRouteChildren: SessionNotesRouteChildren = {
  SessionNotesNoteIdRoute: SessionNotesNoteIdRoute,
}

const SessionNotesRouteWithChildren = SessionNotesRoute._addFileChildren(
  SessionNotesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MentorDashboardRoute: MentorDashboardRoute,
  MentorSignupRoute: MentorSignupRoute,
  MentorTermsRoute: MentorTermsRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionNotesRoute: SessionNotesRouteWithChildren,
  StudentSignupRoute: StudentSignupRoute,
  TermsRoute: TermsRoute,
  MentorIdRoute: MentorIdRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  ParentalConsentTokenRoute: ParentalConsentTokenRoute,
  ApiPublicHooksSendEventEmailRoute: ApiPublicHooksSendEventEmailRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
