-- ════════════════════════════════════════════════════════════════════════════
-- India reference-data seed — PART 1 of 2: universities + academic email domains
-- + top-tier aliases. (Schools + colleges are a separate later build.)
-- ════════════════════════════════════════════════════════════════════════════
-- DATA-ONLY, ADDITIVE, idempotent. No tables/columns/RPCs added (no types.ts change).
-- Generated from the committed source data files (do not hand-edit the row lists):
--   supabase/seed-data/ref_universities_india.csv  (1176 names, normalized-deduped)
--   supabase/seed-data/ref_academic_domains_india.csv  (487 domains)
--
-- The university list is DEDUPED on a normalized key (lowercase, &->and, strip all
-- punctuation, collapse whitespace): rows whose key matches a curated source='seed'
-- row are dropped (curated canonical spelling + aliases win), and generic city-less
-- stubs (a key that is a strict prefix of >=2 others) are removed. So the bulk rows
-- here share NO normalized key with the curated set or each other.
--
-- SOURCES + LICENCES (attribution):
--   • Universities: Bluff-0/UGC_Indian-University-Dataset (MIT) UNION
--     Hipo/university-domains-list India entries (MIT). The official AISHE XLSX
--     (AIKOSH / Ministry of Education, GODL-India) was JS/approval-gated + not
--     machine-fetchable; MIT mirrors are the sanctioned fallback. Bulk tagged
--     source='UGC' (distinct from curated source='seed').
--   • Email domains: Hipo/university-domains-list world JSON (MIT), filtered to India.
--   • Aliases: hand-authored for top institutions, keyed to the exact loaded name,
--     applied ONLY where aliases is empty (never clobbers the curated tier).
--
-- Verification: supabase/dev-seeds/ref-data-india-seed-verification.sql
-- LOCAL-ONLY: hosted Supabase stays on HOLD until the explicit reconciliation step.
-- ════════════════════════════════════════════════════════════════════════════

-- ─── ref_universities — 1176 India names (UGC ∪ Hipo, deduped); ON CONFLICT preserves curated ───
INSERT INTO public.ref_universities (name, country, aliases, source) VALUES
  ('A P Goyal Shimla University', 'India', '{}', 'UGC'),
  ('A.K.S. University', 'India', '{}', 'UGC'),
  ('A.P.J. Abdul Kalam Technological University', 'India', '{}', 'UGC'),
  ('AAFT University of Media and Arts', 'India', '{}', 'UGC'),
  ('AIPH University', 'India', '{}', 'UGC'),
  ('AISECT University', 'India', '{}', 'UGC'),
  ('ARYA Institute of Engineering & Technology', 'India', '{}', 'UGC'),
  ('AURO University of Hospitality and Management', 'India', '{}', 'UGC'),
  ('Abhilashi University', 'India', '{}', 'UGC'),
  ('Academy of Maritime Education and Training', 'India', '{}', 'UGC'),
  ('Acharaya N.G.Ranga Agricultural University', 'India', '{}', 'UGC'),
  ('Acharaya Nagarjuna University', 'India', '{}', 'UGC'),
  ('Acharya Nagarjuna University', 'India', '{}', 'UGC'),
  ('Acharya Ranga Agricultural University', 'India', '{}', 'UGC'),
  ('Adamas University', 'India', '{}', 'UGC'),
  ('Adesh University', 'India', '{}', 'UGC'),
  ('Adichunchanagiri University', 'India', '{}', 'UGC'),
  ('Adikavi Nannaya University', 'India', '{}', 'UGC'),
  ('Aditya University', 'India', '{}', 'UGC'),
  ('Ahmedabad University', 'India', '{}', 'UGC'),
  ('Ajeenkya D.Y. Patil University', 'India', '{}', 'UGC'),
  ('Akal University', 'India', '{}', 'UGC'),
  ('Akkamahadevi women''s University (Formerly known as "Karnataka State Women''s University)', 'India', '{}', 'UGC'),
  ('Al-Falah University', 'India', '{}', 'UGC'),
  ('Al-Karim University', 'India', '{}', 'UGC'),
  ('Alagappa University', 'India', '{}', 'UGC'),
  ('Aliah University', 'India', '{}', 'UGC'),
  ('Aligarh Muslim University', 'India', '{}', 'UGC'),
  ('All India Institute of Medical Sciences', 'India', '{}', 'UGC'),
  ('Allahabad Agricultural Institute, Deemed University', 'India', '{}', 'UGC'),
  ('Allahabad State University', 'India', '{}', 'UGC'),
  ('Allahabad University', 'India', '{}', 'UGC'),
  ('Alliance University', 'India', '{}', 'UGC'),
  ('Alpha College of Engineering', 'India', '{}', 'UGC'),
  ('Ambedkar University Delhi (AUD)', 'India', '{}', 'UGC'),
  ('Amravati University', 'India', '{}', 'UGC'),
  ('Amrita Vishwa Vidyapeetham', 'India', '{}', 'UGC'),
  ('Anand Agricultural University', 'India', '{}', 'UGC'),
  ('Anant National University', 'India', '{}', 'UGC'),
  ('Andhra University', 'India', '{}', 'UGC'),
  ('Anna University of Technology, Tirunelveli', 'India', '{}', 'UGC'),
  ('Annamalai University', 'India', '{}', 'UGC'),
  ('Ansal University', 'India', '{}', 'UGC'),
  ('Anurag University', 'India', '{}', 'UGC'),
  ('Apeejay Stya University', 'India', '{}', 'UGC'),
  ('Apex Professional University', 'India', '{}', 'UGC'),
  ('Apex university', 'India', '{}', 'UGC'),
  ('Arka Jain University', 'India', '{}', 'UGC'),
  ('Arni University', 'India', '{}', 'UGC'),
  ('Arunachal University of Studies', 'India', '{}', 'UGC'),
  ('Arunodaya University', 'India', '{}', 'UGC'),
  ('Arybhatta Knowledge University', 'India', '{}', 'UGC'),
  ('Asansol Engineering College', 'India', '{}', 'UGC'),
  ('Assam Agricultural University', 'India', '{}', 'UGC'),
  ('Assam Don Bosco University', 'India', '{}', 'UGC'),
  ('Assam Down Town University', 'India', '{}', 'UGC'),
  ('Assam Rajiv Gandhi University of Co-operative Management', 'India', '{}', 'UGC'),
  ('Assam Science & Technology University', 'India', '{}', 'UGC'),
  ('Assam University', 'India', '{}', 'UGC'),
  ('Assam Women''s University', 'India', '{}', 'UGC'),
  ('Atal Bihari Bajpayee Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Atal Bihari Vajpayee Hindi Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Atal Bihari Vajpayee Indian Institute of Information Technology and Management, Gwalior', 'India', '{}', 'UGC'),
  ('Atharva College of Engineering', 'India', '{}', 'UGC'),
  ('Atmiya University', 'India', '{}', 'UGC'),
  ('Avantika University', 'India', '{}', 'UGC'),
  ('Avinashilingam Institute for Home Science and Higher Education for Women', 'India', '{}', 'UGC'),
  ('Awadesh Pratap Singh University', 'India', '{}', 'UGC'),
  ('Awadhesh Pratap Singh University', 'India', '{}', 'UGC'),
  ('Ayush and Health Sciences University of Chhattisgarh', 'India', '{}', 'UGC'),
  ('Azim Premji University', 'India', '{}', 'UGC'),
  ('B. R. Ambedkar Bihar University', 'India', '{}', 'UGC'),
  ('B. S. Abdur Rahman University', 'India', '{}', 'UGC'),
  ('B.L.D.E.', 'India', '{}', 'UGC'),
  ('B.R.Ambedkar National Institute of Technology', 'India', '{}', 'UGC'),
  ('B.S. Abdur Rahman Institute of Science and Technology', 'India', '{}', 'UGC'),
  ('BML Munjal University', 'India', '{}', 'UGC'),
  ('Baba Farid University of Health Sciences', 'India', '{}', 'UGC'),
  ('Baba Ghulam Shah Badshah University', 'India', '{}', 'UGC'),
  ('Baba MastNath University', 'India', '{}', 'UGC'),
  ('Babasaheb Bhimrao Ambedkar Bihar University', 'India', '{}', 'UGC'),
  ('Babasaheb Bhimrao Ambedkar University', 'India', '{}', 'UGC'),
  ('Babu Banarasi Das University', 'India', '{}', 'UGC'),
  ('Baddi University of Emerging Sciences & Technology', 'India', '{}', 'UGC'),
  ('Bahra University', 'India', '{}', 'UGC'),
  ('Banasthai Vidyapith', 'India', '{}', 'UGC'),
  ('Banasthali University', 'India', '{}', 'UGC'),
  ('Banda University of Agriculture & Technology', 'India', '{}', 'UGC'),
  ('Bangalore University', 'India', '{}', 'UGC'),
  ('Bankura University', 'India', '{}', 'UGC'),
  ('Bareilly International University', 'India', '{}', 'UGC'),
  ('Barkatullaah University', 'India', '{}', 'UGC'),
  ('Barkatullah University', 'India', '{}', 'UGC'),
  ('Bastar Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Bengal Engineering College', 'India', '{}', 'UGC'),
  ('Bengaluru Central University', 'India', '{}', 'UGC'),
  ('Bengaluru North University', 'India', '{}', 'UGC'),
  ('Bennett University', 'India', '{}', 'UGC'),
  ('Berhampur University', 'India', '{}', 'UGC'),
  ('Bhabha University', 'India', '{}', 'UGC'),
  ('Bhagat Phool Singh Mahila Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Bhagwan Parshuram Institute of Technology', 'India', '{}', 'UGC'),
  ('Bhagwant Global University', 'India', '{}', 'UGC'),
  ('Bhagwant University', 'India', '{}', 'UGC'),
  ('Bhakta Kavi Narsinh Mehta University', 'India', '{}', 'UGC'),
  ('Bharath Institue Of Higher Education & Research', 'India', '{}', 'UGC'),
  ('Bharath Institute of Higher Education & Research', 'India', '{}', 'UGC'),
  ('Bharathiar University', 'India', '{}', 'UGC'),
  ('Bharathidasan University', 'India', '{}', 'UGC'),
  ('Bharati Vidyapeeth', 'India', '{}', 'UGC'),
  ('Bharati Vidyapeeth University', 'India', '{}', 'UGC'),
  ('Bharatiya Engineering Science and Technology Innovation University', 'India', '{}', 'UGC'),
  ('Bhartiya Skill Development University', 'India', '{}', 'UGC'),
  ('Bhatkhande Music Institute', 'India', '{}', 'UGC'),
  ('Bhavnagar University', 'India', '{}', 'UGC'),
  ('Bhupal Nobles University', 'India', '{}', 'UGC'),
  ('Bhupender Narayan Mandal University', 'India', '{}', 'UGC'),
  ('Bhupendra Narayan Mandal University', 'India', '{}', 'UGC'),
  ('Bidhan Chandra Agricultural University', 'India', '{}', 'UGC'),
  ('Bidhan Chandra Krishi Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Bihar Agricultural University', 'India', '{}', 'UGC'),
  ('Bihar Animal Sciences University', 'India', '{}', 'UGC'),
  ('Biju Patnaik University of Technology', 'India', '{}', 'UGC'),
  ('Biju Pattnaik University of Technology', 'India', '{}', 'UGC'),
  ('Bikaner Technical University', 'India', '{}', 'UGC'),
  ('Binod Bihari Mahto Koylanchal University', 'India', '{}', 'UGC'),
  ('Birla Global University', 'India', '{}', 'UGC'),
  ('Birla Institute of Technology', 'India', '{}', 'UGC'),
  ('Birla Institute of Technology and Science', 'India', '{}', 'UGC'),
  ('Birla Institute of Technology, Ranchi', 'India', '{}', 'UGC'),
  ('Birsa Agricultural University', 'India', '{}', 'UGC'),
  ('Birsa Munda Tribal University', 'India', '{}', 'UGC'),
  ('Bishop Herber College', 'India', '{}', 'UGC'),
  ('Bodoland University', 'India', '{}', 'UGC'),
  ('Brainware University', 'India', '{}', 'UGC'),
  ('Bundelkhand University', 'India', '{}', 'UGC'),
  ('Burdwan University', 'India', '{}', 'UGC'),
  ('C. U. Shah University', 'India', '{}', 'UGC'),
  ('CCS Haryana Agricultural University', 'India', '{}', 'UGC'),
  ('CEPT University', 'India', '{}', 'UGC'),
  ('CMJ University', 'India', '{}', 'UGC'),
  ('CMR University', 'India', '{}', 'UGC'),
  ('COEP Technological University', 'India', '{}', 'UGC'),
  ('COER University Roorkee', 'India', '{}', 'UGC'),
  ('CT University', 'India', '{}', 'UGC'),
  ('Calcutta University', 'India', '{}', 'UGC'),
  ('Calicut University', 'India', '{}', 'UGC'),
  ('Calorx Teacher''s University', 'India', '{}', 'UGC'),
  ('Capital University', 'India', '{}', 'UGC'),
  ('Career Point University', 'India', '{}', 'UGC'),
  ('Center for Entrepreneurship and Small Business Management', 'India', '{}', 'UGC'),
  ('Central Agricultural University', 'India', '{}', 'UGC'),
  ('Central Institute of Buddhist Studies(CIBS)', 'India', '{}', 'UGC'),
  ('Central Institute of English and Foreign Languages', 'India', '{}', 'UGC'),
  ('Central Institute of Fisheries Education', 'India', '{}', 'UGC'),
  ('Central Institute of Higher Tibetan Studies', 'India', '{}', 'UGC'),
  ('Central Institute of Technology(CIT)', 'India', '{}', 'UGC'),
  ('Central University of Gujarat', 'India', '{}', 'UGC'),
  ('Central University of Haryana', 'India', '{}', 'UGC'),
  ('Central University of Himachal Pradesh', 'India', '{}', 'UGC'),
  ('Central University of Jammu', 'India', '{}', 'UGC'),
  ('Central University of Jharkhand', 'India', '{}', 'UGC'),
  ('Central University of Karnataka', 'India', '{}', 'UGC'),
  ('Central University of Kashmir', 'India', '{}', 'UGC'),
  ('Central University of Kerala', 'India', '{}', 'UGC'),
  ('Central University of Orissa', 'India', '{}', 'UGC'),
  ('Central University of Punjab', 'India', '{}', 'UGC'),
  ('Central University of Rajasthan', 'India', '{}', 'UGC'),
  ('Central University of South Bihar', 'India', '{}', 'UGC'),
  ('Central university of Tamil Nadu', 'India', '{}', 'UGC'),
  ('Centurion University of Technolgy and Management', 'India', '{}', 'UGC'),
  ('Centurion University of Technology and Management', 'India', '{}', 'UGC'),
  ('Ch. Bansi Lal University', 'India', '{}', 'UGC'),
  ('Ch. Charan Singh University', 'India', '{}', 'UGC'),
  ('Chanakya National Law University', 'India', '{}', 'UGC'),
  ('Chandigarh University', 'India', '{}', 'UGC'),
  ('Chandil Polytechnic School', 'India', '{}', 'UGC'),
  ('Chandr Shekhar Azad University of Agriculture & Technology', 'India', '{}', 'UGC'),
  ('Chandra Shekhar Azad University of Agriculture and Technology', 'India', '{}', 'UGC'),
  ('Charotar University of Science and Technology', 'India', '{}', 'UGC'),
  ('Chatrapati Sahuji Maharaj Kanpur University', 'India', '{}', 'UGC'),
  ('Chaudhary Charan Singh University', 'India', '{}', 'UGC'),
  ('Chaudhary Devi Lal University', 'India', '{}', 'UGC'),
  ('Chaudhary Ranbir Singh University', 'India', '{}', 'UGC'),
  ('Chaudhary Sarwan Kumar Himachal Pradesh Krishi Vishvavidyalaya', 'India', '{}', 'UGC'),
  ('Chennai Institute of Technology', 'India', '{}', 'UGC'),
  ('Chennai Mathematical Institute', 'India', '{}', 'UGC'),
  ('Chettinad Academy of Research and Education (CARE)', 'India', '{}', 'UGC'),
  ('Chhatrapati Shahu Ji Maharaj University', 'India', '{}', 'UGC'),
  ('Chhatrapati Shivaji Maharaj University', 'India', '{}', 'UGC'),
  ('Chhattisgarh Kamdhenu Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Chhattisgarh Swami Vivekanad Technical Universty', 'India', '{}', 'UGC'),
  ('Children''s University', 'India', '{}', 'UGC'),
  ('Chinmaya Vishwavidyapeeth', 'India', '{}', 'UGC'),
  ('Chitkara University', 'India', '{}', 'UGC'),
  ('Choudary Charan Singh Haryana Agricultural Univeersity', 'India', '{}', 'UGC'),
  ('Choudary Charan Singh University', 'India', '{}', 'UGC'),
  ('Cluster University of Jammu', 'India', '{}', 'UGC'),
  ('Cluster University of Srinagar', 'India', '{}', 'UGC'),
  ('Cochin University of Science and Technology', 'India', '{}', 'UGC'),
  ('Cochin Unviersity of Science & Technology', 'India', '{}', 'UGC'),
  ('Cooch Behar Panchanan Barma University', 'India', '{}', 'UGC'),
  ('Cotton University', 'India', '{}', 'UGC'),
  ('D Y Patil International University', 'India', '{}', 'UGC'),
  ('D.A.V University', 'India', '{}', 'UGC'),
  ('D.Y Patil Educational Society', 'India', '{}', 'UGC'),
  ('DAV Institute of Engineering & Technology', 'India', '{}', 'UGC'),
  ('DIT University', 'India', '{}', 'UGC'),
  ('Dakshina Bharat Hindi Prachar Sabha', 'India', '{}', 'UGC'),
  ('Damodaram Sanjivayya National Law University', 'India', '{}', 'UGC'),
  ('Darul Huda Islamic University', 'India', '{}', 'UGC'),
  ('Datta Meghe Institute of Medical Sciences', 'India', '{}', 'UGC'),
  ('Dav University', 'India', '{}', 'UGC'),
  ('Davangere University', 'India', '{}', 'UGC'),
  ('Dayalbagh Educational Institute', 'India', '{}', 'UGC'),
  ('Dayananda Sagar University', 'India', '{}', 'UGC'),
  ('Deccan College Postgraduate and Research Institute', 'India', '{}', 'UGC'),
  ('Deen Bandhu Chhotu Ram University of Sciences & Technology', 'India', '{}', 'UGC'),
  ('Deen Dayal Upadhyay Gorakhpur University', 'India', '{}', 'UGC'),
  ('Defence Institute of Advanced Technology', 'India', '{}', 'UGC'),
  ('Delhi College of Engineering (DCE)', 'India', '{}', 'UGC'),
  ('Delhi Pharmaceutical Sciences & Research University', 'India', '{}', 'UGC'),
  ('Desh Bhagat University', 'India', '{}', 'UGC'),
  ('Dev Sanakrit Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Devi Ahilya University of Indore', 'India', '{}', 'UGC'),
  ('Devi Ahilya Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Dhanamanjuri University', 'India', '{}', 'UGC'),
  ('Dharamsinh Desai University', 'India', '{}', 'UGC'),
  ('Dharmashastra National Law University', 'India', '{}', 'UGC'),
  ('Dharmsinh Desai University', 'India', '{}', 'UGC'),
  ('Dhirubhai Ambani Institute of Information and Communication Technology', 'India', '{}', 'UGC'),
  ('Diamond Harbour Women''s University', 'India', '{}', 'UGC'),
  ('Dibrugarh University', 'India', '{}', 'UGC'),
  ('Doon University', 'India', '{}', 'UGC'),
  ('Dr C V Raman University', 'India', '{}', 'UGC'),
  ('Dr K N Modi University', 'India', '{}', 'UGC'),
  ('Dr Shyama Prasad Mukherjee University', 'India', '{}', 'UGC'),
  ('Dr. A.P.J Abdul Kalam University', 'India', '{}', 'UGC'),
  ('Dr. A.P.J. Abdul Kalam Technical University', 'India', '{}', 'UGC'),
  ('Dr. Abdul Haq Urdu University', 'India', '{}', 'UGC'),
  ('Dr. B. R. Ambedkar National Institute of Technology Jalandhar', 'India', '{}', 'UGC'),
  ('Dr. B. R. Ambedkar University of Social Sciences', 'India', '{}', 'UGC'),
  ('Dr. B.R. Ambedkar National Law University', 'India', '{}', 'UGC'),
  ('Dr. B.R.Ambedkar Open University', 'India', '{}', 'UGC'),
  ('Dr. B.R.Ambedkar University', 'India', '{}', 'UGC'),
  ('Dr. Babasaheb Ambedkar Marathwada University', 'India', '{}', 'UGC'),
  ('Dr. Babasaheb Ambedkar Marathwada Universtiy', 'India', '{}', 'UGC'),
  ('Dr. Babasaheb Ambedkar Open University', 'India', '{}', 'UGC'),
  ('Dr. Babasaheb Ambedkar Technological University', 'India', '{}', 'UGC'),
  ('Dr. Babasaheb AmbedkarTechnological University', 'India', '{}', 'UGC'),
  ('Dr. Bhim Rao Abdekar University', 'India', '{}', 'UGC'),
  ('Dr. Bhimrao Ambedkar Law University', 'India', '{}', 'UGC'),
  ('Dr. D.Y. Patil University', 'India', '{}', 'UGC'),
  ('Dr. D.Y. Patil Vidyapeeth', 'India', '{}', 'UGC'),
  ('Dr. Hari Singh Gour University, formerly University of Sagar', 'India', '{}', 'UGC'),
  ('Dr. Harisingh Gour Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Dr. M.G.R. Educational and Research Institute', 'India', '{}', 'UGC'),
  ('Dr. N.T.R. University of Health Sciences', 'India', '{}', 'UGC'),
  ('Dr. Panjabrao Deshmukh Krishi Vidyapeeth', 'India', '{}', 'UGC'),
  ('Dr. Punjabrao Deshmukh Krishi Vidyapeeth', 'India', '{}', 'UGC'),
  ('Dr. Ram Manohar Lohia Avadh University', 'India', '{}', 'UGC'),
  ('Dr. Ram Manohar Lohia Awadh University', 'India', '{}', 'UGC'),
  ('Dr. Ram Manohar Lohia Institute of Medical Sciences', 'India', '{}', 'UGC'),
  ('Dr. Ram Manohar Lohiya National Law University', 'India', '{}', 'UGC'),
  ('Dr. Shakuntala Misra National Rehabilitation University', 'India', '{}', 'UGC'),
  ('Dr. Shyama Prasad University', 'India', '{}', 'UGC'),
  ('Dr. Sudhir Chandra Sur Institute of Technology & Sports Complex', 'India', '{}', 'UGC'),
  ('Dr. Vishwanath Karad MIT World Peace University', 'India', '{}', 'UGC'),
  ('Dr. Y.S.Parmar University of Horticulture & Forestry', 'India', '{}', 'UGC'),
  ('Dr. Y.S.R. Horticultural Univerity', 'India', '{}', 'UGC'),
  ('Dr. YS Parmar University of Horticulture and Forestry', 'India', '{}', 'UGC'),
  ('Dravidian University', 'India', '{}', 'UGC'),
  ('Easwari Engineering College', 'India', '{}', 'UGC'),
  ('Eiilm University', 'India', '{}', 'UGC'),
  ('English & Foreign Languages University', 'India', '{}', 'UGC'),
  ('Era University', 'India', '{}', 'UGC'),
  ('Eternal University', 'India', '{}', 'UGC'),
  ('Fakir Mohan University', 'India', '{}', 'UGC'),
  ('Fatima Mata National College', 'India', '{}', 'UGC'),
  ('First Global University to teaching Jainism', 'India', '{}', 'UGC'),
  ('Flame University', 'India', '{}', 'UGC'),
  ('Forest Research Institute', 'India', '{}', 'UGC'),
  ('Forest Research Institute Dehradun', 'India', '{}', 'UGC'),
  ('G L A University', 'India', '{}', 'UGC'),
  ('G.B.Pant University of Agriculture & Technology', 'India', '{}', 'UGC'),
  ('G.H Raisoni University', 'India', '{}', 'UGC'),
  ('G.L.S. University', 'India', '{}', 'UGC'),
  ('GD Goenka University', 'India', '{}', 'UGC'),
  ('GNA University', 'India', '{}', 'UGC'),
  ('GSFC University', 'India', '{}', 'UGC'),
  ('Galgotias University', 'India', '{}', 'UGC'),
  ('Gandhi Institute of Engineering & Technology University.', 'India', '{}', 'UGC'),
  ('Gandhi Institute of Technology and Management (GITAM)', 'India', '{}', 'UGC'),
  ('Gandhi Institute of Technology and Managment', 'India', '{}', 'UGC'),
  ('Gangadhar Meher University', 'India', '{}', 'UGC'),
  ('Ganpat University', 'India', '{}', 'UGC'),
  ('Garden City University', 'India', '{}', 'UGC'),
  ('Gauhati University', 'India', '{}', 'UGC'),
  ('Gautam Buddha University', 'India', '{}', 'UGC'),
  ('Geetanjali University', 'India', '{}', 'UGC'),
  ('Global Open University , Nagaland', 'India', '{}', 'UGC'),
  ('Goa University', 'India', '{}', 'UGC'),
  ('Gokhale Institute of Politics and Economics', 'India', '{}', 'UGC'),
  ('Gokul Global University', 'India', '{}', 'UGC'),
  ('Gola Polytechnic School', 'India', '{}', 'UGC'),
  ('Gondwana University', 'India', '{}', 'UGC'),
  ('Gopal Narayan Singh University', 'India', '{}', 'UGC'),
  ('Govind Ballabh Pant University of Agriculture and Technology', 'India', '{}', 'UGC'),
  ('Govind Guru Tribal University', 'India', '{}', 'UGC'),
  ('Graphic Era', 'India', '{}', 'UGC'),
  ('Graphic Era Hill University', 'India', '{}', 'UGC'),
  ('Greater Kolkata College of Engineering & Management', 'India', '{}', 'UGC'),
  ('Gujarat Ayurved University', 'India', '{}', 'UGC'),
  ('Gujarat Ayurveda University', 'India', '{}', 'UGC'),
  ('Gujarat Forensic Sciences University', 'India', '{}', 'UGC'),
  ('Gujarat Maritime University', 'India', '{}', 'UGC'),
  ('Gujarat National Law University', 'India', '{}', 'UGC'),
  ('Gujarat Technological University', 'India', '{}', 'UGC'),
  ('Gujarat Technological University Ahmedabad', 'India', '{}', 'UGC'),
  ('Gujarat University', 'India', '{}', 'UGC'),
  ('Gujarat University Ahmedabad', 'India', '{}', 'UGC'),
  ('Gujarat University of Transplantation Sciences', 'India', '{}', 'UGC'),
  ('Gujarat Vidyapith', 'India', '{}', 'UGC'),
  ('Gulbarga University', 'India', '{}', 'UGC'),
  ('Guru Angad Dev Veterinary & Animal Sciences University', 'India', '{}', 'UGC'),
  ('Guru Ghasidas University', 'India', '{}', 'UGC'),
  ('Guru Ghasidas Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Guru Gobind Singh Indraprastha University', 'India', '{}', 'UGC'),
  ('Guru Gobind Singh Indraprastha Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Guru Jambeshwar University', 'India', '{}', 'UGC'),
  ('Guru Jambeshwar University of Science and Technology', 'India', '{}', 'UGC'),
  ('Guru Kashi University', 'India', '{}', 'UGC'),
  ('Guru Nanak Dev University', 'India', '{}', 'UGC'),
  ('Guru Nanak Institute of Dental Sciences & Research', 'India', '{}', 'UGC'),
  ('Guru Nanak Institute of Hotel Management', 'India', '{}', 'UGC'),
  ('Guru Nanak Institute of Pharmaceutical Science & Technology', 'India', '{}', 'UGC'),
  ('Guru Nanak Institute of Technology', 'India', '{}', 'UGC'),
  ('Guru Ravidas Ayurved University', 'India', '{}', 'UGC'),
  ('Gurugram University', 'India', '{}', 'UGC'),
  ('Gurukul Kangri vidyapeeth', 'India', '{}', 'UGC'),
  ('Gurukul University', 'India', '{}', 'UGC'),
  ('Gurukula Kangri University', 'India', '{}', 'UGC'),
  ('Harcourt Butler Technical University', 'India', '{}', 'UGC'),
  ('Haridev Joshi University of Journalism and Mass Communication', 'India', '{}', 'UGC'),
  ('Haryana Vishwakarma Skill University', 'India', '{}', 'UGC'),
  ('Hemchand Yadav Vishwavidyalaya(Earlier known as Durg Vishwavidyalaya)', 'India', '{}', 'UGC'),
  ('Hemchandracharay North Gujarat University', 'India', '{}', 'UGC'),
  ('Hemchandracharya North Gujarat University', 'India', '{}', 'UGC'),
  ('Hemwati Nandan Bahuguna Garhwal University', 'India', '{}', 'UGC'),
  ('Hemwati Nandan Bahuguna Medical Education University', 'India', '{}', 'UGC'),
  ('Hidayatullah National Law University', 'India', '{}', 'UGC'),
  ('Hidayatullah National Law University, Raipur', 'India', '{}', 'UGC'),
  ('Himachal Pradesh Agricultural University', 'India', '{}', 'UGC'),
  ('Himachal Pradesh National Law University', 'India', '{}', 'UGC'),
  ('Himachal Pradesh Technical University', 'India', '{}', 'UGC'),
  ('Himachal Pradesh University', 'India', '{}', 'UGC'),
  ('Himalayan Garhwal University', 'India', '{}', 'UGC'),
  ('Himalayan University', 'India', '{}', 'UGC'),
  ('Himgiri Zee University', 'India', '{}', 'UGC'),
  ('Hindustan Institute of Technology and Science', 'India', '{}', 'UGC'),
  ('Homi Bhabha National Institute Regd. Office', 'India', '{}', 'UGC'),
  ('Homoeopathy University', 'India', '{}', 'UGC'),
  ('I.E.C. (India Education Centre) University', 'India', '{}', 'UGC'),
  ('IASE (Institute of Advanced Studies) Deemed University', 'India', '{}', 'UGC'),
  ('ICFAI Foundation for Higher Education', 'India', '{}', 'UGC'),
  ('ICFAI University', 'India', '{}', 'UGC'),
  ('ICFAI University, Dehradun', 'India', '{}', 'UGC'),
  ('ICFAI University, Himachal Pradesh', 'India', '{}', 'UGC'),
  ('ICFAI University, Hyderabad', 'India', '{}', 'UGC'),
  ('ICFAI University, Jaipur', 'India', '{}', 'UGC'),
  ('ICFAI University, Jharkhand', 'India', '{}', 'UGC'),
  ('ICFAI University, Meghalaya', 'India', '{}', 'UGC'),
  ('ICFAI University, Mizoram', 'India', '{}', 'UGC'),
  ('ICFAI University, Nagaland', 'India', '{}', 'UGC'),
  ('ICFAI University, Raipur', 'India', '{}', 'UGC'),
  ('ICFAI University, Sikkim', 'India', '{}', 'UGC'),
  ('ICFAI University, Tripura', 'India', '{}', 'UGC'),
  ('IFTM University', 'India', '{}', 'UGC'),
  ('IIHMR University', 'India', '{}', 'UGC'),
  ('IILM University', 'India', '{}', 'UGC'),
  ('IIMT University', 'India', '{}', 'UGC'),
  ('IIT Bhubaneswar', 'India', '{}', 'UGC'),
  ('IMS Unison University', 'India', '{}', 'UGC'),
  ('ISBM University', 'India', '{}', 'UGC'),
  ('ITM University', 'India', '{}', 'UGC'),
  ('ITM Vocational University', 'India', '{}', 'UGC'),
  ('Indain Institute of Foreigen Trade', 'India', '{}', 'UGC'),
  ('Indian Agricultural Research Institute', 'India', '{}', 'UGC'),
  ('Indian Association for the Cultivation of Science (IACS)', 'India', '{}', 'UGC'),
  ('Indian Board of Alternative Medicine', 'India', '{}', 'UGC'),
  ('Indian Institute of Information Technology Allahabad', 'India', '{}', 'UGC'),
  ('Indian Institute of Information Technology Sri City', 'India', '{}', 'UGC'),
  ('Indian Institute of Information Technology and Management', 'India', '{}', 'UGC'),
  ('Indian Institute of Information Technology and Management - Kerala', 'India', '{}', 'UGC'),
  ('Indian Institute of Information Technology, Guwahati', 'India', '{}', 'UGC'),
  ('Indian Institute of Information Technology, Kota', 'India', '{}', 'UGC'),
  ('Indian Institute of Information Technology, Vadodara', 'India', '{}', 'UGC'),
  ('Indian Institute of Information Technology,Design & Manufacturing(IIITDM)', 'India', '{}', 'UGC'),
  ('Indian Institute of Management, Tiruchirappalli', 'India', '{}', 'UGC'),
  ('Indian Institute of Public Health', 'India', '{}', 'UGC'),
  ('Indian Institute of Space Science and Technology', 'India', '{}', 'UGC'),
  ('Indian Institute of Teacher Education', 'India', '{}', 'UGC'),
  ('Indian Institute of Technology Ropar', 'India', '{}', 'UGC'),
  ('Indian Institute of Technology, Gandhinagar', 'India', '{}', 'UGC'),
  ('Indian Institute of Technology, Jodhpur', 'India', '{}', 'UGC'),
  ('Indian Institute of Technology, Patna', 'India', '{}', 'UGC'),
  ('Indian Law Institue', 'India', '{}', 'UGC'),
  ('Indian Law Institute', 'India', '{}', 'UGC'),
  ('Indian Maritime University', 'India', '{}', 'UGC'),
  ('Indian School of Business Management and Administration', 'India', '{}', 'UGC'),
  ('Indian School of Mines (ISM)', 'India', '{}', 'UGC'),
  ('Indian Statistical Institute', 'India', '{}', 'UGC'),
  ('Indian University', 'India', '{}', 'UGC'),
  ('Indian Veterinary Research Institute', 'India', '{}', 'UGC'),
  ('Indira Gandhi Agricultural University', 'India', '{}', 'UGC'),
  ('Indira Gandhi Delhi Technical University for Women', 'India', '{}', 'UGC'),
  ('Indira Gandhi Institute of Development Research', 'India', '{}', 'UGC'),
  ('Indira Gandhi Institute of Development and Research', 'India', '{}', 'UGC'),
  ('Indira Gandhi Institute of Medical Sciences', 'India', '{}', 'UGC'),
  ('Indira Gandhi Krishi Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Indira Gandhi National Open University', 'India', '{}', 'UGC'),
  ('Indira Gandhi Technological and Medical Science University', 'India', '{}', 'UGC'),
  ('Indira Gandhi University', 'India', '{}', 'UGC'),
  ('Indira Kala Sangeet Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Indraprastha Institute of Information Technology', 'India', '{}', 'UGC'),
  ('Indrashil University', 'India', '{}', 'UGC'),
  ('Indus International Uniersity', 'India', '{}', 'UGC'),
  ('Indus University', 'India', '{}', 'UGC'),
  ('Institute of Advanced Research', 'India', '{}', 'UGC'),
  ('Institute of Advanced Studies in Education', 'India', '{}', 'UGC'),
  ('Institute of Chemical Technology', 'India', '{}', 'UGC'),
  ('Institute of Infrastructure Technology Research and Management', 'India', '{}', 'UGC'),
  ('Institute of Management Studies', 'India', '{}', 'UGC'),
  ('Institute of Technology and Management', 'India', '{}', 'UGC'),
  ('Institute of Trans-Disciplinary Health Sciences and Technology', 'India', '{}', 'UGC'),
  ('Institute of liver and Biliary Sciences', 'India', '{}', 'UGC'),
  ('Integral University', 'India', '{}', 'UGC'),
  ('International Institute for Population Sciences', 'India', '{}', 'UGC'),
  ('International Institute of Information Technology, Bangalore', 'India', '{}', 'UGC'),
  ('International Institute of Information Technology, Bhubaneswar', 'India', '{}', 'UGC'),
  ('International Institute of Information Technology, Pune', 'India', '{}', 'UGC'),
  ('Invertis University', 'India', '{}', 'UGC'),
  ('Islamic University of Sciences & Technology University', 'India', '{}', 'UGC'),
  ('J.E.C.R.C University', 'India', '{}', 'UGC'),
  ('J.S. University', 'India', '{}', 'UGC'),
  ('JIS College of Engineering', 'India', '{}', 'UGC'),
  ('JIS Institute of Advanced Studies & Research', 'India', '{}', 'UGC'),
  ('JIS Institute of Pharmacy', 'India', '{}', 'UGC'),
  ('JIS School of Medical Science & Research', 'India', '{}', 'UGC'),
  ('JIS School of Polytechnic', 'India', '{}', 'UGC'),
  ('JIS University', 'India', '{}', 'UGC'),
  ('JK Lakshmipat University', 'India', '{}', 'UGC'),
  ('JSS Academy of Higher Education & Research', 'India', '{}', 'UGC'),
  ('JSS Science & Technology University', 'India', '{}', 'UGC'),
  ('Jagadgura Rambhadracharya Handicapped University', 'India', '{}', 'UGC'),
  ('Jagadguru Ramanandacharya Sanskrit University', 'India', '{}', 'UGC'),
  ('Jagan Nath University', 'India', '{}', 'UGC'),
  ('Jagannath University', 'India', '{}', 'UGC'),
  ('Jagran Lakecity University', 'India', '{}', 'UGC'),
  ('Jai Naraim Vyas University', 'India', '{}', 'UGC'),
  ('Jai Narain Vyas University', 'India', '{}', 'UGC'),
  ('Jai Prakash University', 'India', '{}', 'UGC'),
  ('Jai Prakash vishwavidyalaya(university)', 'India', '{}', 'UGC'),
  ('Jain (Deemed-to-be University)', 'India', '{}', 'UGC'),
  ('Jain Vishva Bharati Institute', 'India', '{}', 'UGC'),
  ('Jaipur National University', 'India', '{}', 'UGC'),
  ('Jamia Hamdard', 'India', '{}', 'UGC'),
  ('Jamia Hamdard University', 'India', '{}', 'UGC'),
  ('Jamia Millia Islamia', 'India', '{}', 'UGC'),
  ('Jamia Millia Islamia University', 'India', '{}', 'UGC'),
  ('Jammu University', 'India', '{}', 'UGC'),
  ('Jananayak Chandrashekhar University', 'India', '{}', 'UGC'),
  ('Janardan Rai Nagar Rajasthan Vidyapeeth', 'India', '{}', 'UGC'),
  ('Jawahar lal Nehru Centre for Advanced Scientific Research', 'India', '{}', 'UGC'),
  ('Jawaharlal Nehru Agricultural University', 'India', '{}', 'UGC'),
  ('Jawaharlal Nehru Architecture and Fine Arts University', 'India', '{}', 'UGC'),
  ('Jawaharlal Nehru Centre for Advanced Scientific Research', 'India', '{}', 'UGC'),
  ('Jawaharlal Nehru Krishi Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Jawaharlal Nehru Technological University', 'India', '{}', 'UGC'),
  ('Jawaharlal Nehru Technological University Hyderabad', 'India', '{}', 'UGC'),
  ('Jayoti Vidyapeet Women''s University', 'India', '{}', 'UGC'),
  ('Jaypee Institute of Information Technology', 'India', '{}', 'UGC'),
  ('Jaypee University', 'India', '{}', 'UGC'),
  ('Jaypee University of Engineering & Technology', 'India', '{}', 'UGC'),
  ('Jaypee University of Information Technology', 'India', '{}', 'UGC'),
  ('Jeppiar Engineering College', 'India', '{}', 'UGC'),
  ('Jharkhand Rai University', 'India', '{}', 'UGC'),
  ('Jharkhand Raksha Shakti University', 'India', '{}', 'UGC'),
  ('Jharkhand University of Technology', 'India', '{}', 'UGC'),
  ('Jiwaji University', 'India', '{}', 'UGC'),
  ('Jodhpur National University', 'India', '{}', 'UGC'),
  ('Junagarh Agricultural University', 'India', '{}', 'UGC'),
  ('K K University', 'India', '{}', 'UGC'),
  ('K.L.E. Academy of Higher Education and Research', 'India', '{}', 'UGC'),
  ('K.R. Mangalam University', 'India', '{}', 'UGC'),
  ('KCG College of Technology', 'India', '{}', 'UGC'),
  ('KIET Group of Institutions', 'India', '{}', 'UGC'),
  ('KLE Technological University', 'India', '{}', 'UGC'),
  ('KREA University', 'India', '{}', 'UGC'),
  ('KSGH Music and Performing Arts University', 'India', '{}', 'UGC'),
  ('Kadi Sarva Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Kakatiya University', 'India', '{}', 'UGC'),
  ('Kalasalingam Academy of Research and Education', 'India', '{}', 'UGC'),
  ('Kalinga Institute of Industrial Technology', 'India', '{}', 'UGC'),
  ('Kalinga University', 'India', '{}', 'UGC'),
  ('Kaloji Narayan Rao University of Health Sciences', 'India', '{}', 'UGC'),
  ('Kaloji Narayana Rao University of Health Sciences', 'India', '{}', 'UGC'),
  ('Kalyani University', 'India', '{}', 'UGC'),
  ('Kamdhenu University', 'India', '{}', 'UGC'),
  ('Kameshwar Singh Darbhanga Sanskrit University', 'India', '{}', 'UGC'),
  ('Kameshwar Singh.Darbhanga Sanskrit Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Kannada University', 'India', '{}', 'UGC'),
  ('Kannur University', 'India', '{}', 'UGC'),
  ('Karanataka State Law University', 'India', '{}', 'UGC'),
  ('Karanataka State Open University', 'India', '{}', 'UGC'),
  ('Karanataka University', 'India', '{}', 'UGC'),
  ('Karanataka Veterinary Animal & Fisheries Science University', 'India', '{}', 'UGC'),
  ('Karnatak University', 'India', '{}', 'UGC'),
  ('Karnataka Folklore University', 'India', '{}', 'UGC'),
  ('Karnataka Sanskrit University', 'India', '{}', 'UGC'),
  ('Karnataka State Law University', 'India', '{}', 'UGC'),
  ('Karnataka State Open University', 'India', '{}', 'UGC'),
  ('Karnataka State Rural Development and Panchayat Raj University', 'India', '{}', 'UGC'),
  ('Karnavati University', 'India', '{}', 'UGC'),
  ('Karpagam Academy of Higher Education', 'India', '{}', 'UGC'),
  ('Karpagam University', 'India', '{}', 'UGC'),
  ('Karunya Institute Of Technology', 'India', '{}', 'UGC'),
  ('Karunya Institute of Technology and Sciences', 'India', '{}', 'UGC'),
  ('Kashmir University', 'India', '{}', 'UGC'),
  ('Kavayitri Bahinabai Chadhari North Maharashtra University', 'India', '{}', 'UGC'),
  ('Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Kazi Nazrul University', 'India', '{}', 'UGC'),
  ('Kerala Agricultural University', 'India', '{}', 'UGC'),
  ('Kerala Agricultural Unviersity', 'India', '{}', 'UGC'),
  ('Kerala Kalamandalam', 'India', '{}', 'UGC'),
  ('Kerala University', 'India', '{}', 'UGC'),
  ('Kerala University of Fisheries & Ocean Studies', 'India', '{}', 'UGC'),
  ('Kerala University of Fisheries and Ocean Sciences', 'India', '{}', 'UGC'),
  ('Kerala University of Health Sciences', 'India', '{}', 'UGC'),
  ('Kerala Veterinary & Animal Sciences University', 'India', '{}', 'UGC'),
  ('Khaja Bandanawaz University', 'India', '{}', 'UGC'),
  ('Khallikote University', 'India', '{}', 'UGC'),
  ('Khwaja Moinuddin Chishti Urdu Arabi-Farsi University', 'India', '{}', 'UGC'),
  ('King Georges Medical University', 'India', '{}', 'UGC'),
  ('Kohinoor School of Hospitality Management', 'India', '{}', 'UGC'),
  ('Kolhan University', 'India', '{}', 'UGC'),
  ('Koneru Lakshmaiah Education Foundation', 'India', '{}', 'UGC'),
  ('Konkan Agricultural University', 'India', '{}', 'UGC'),
  ('Konkan Krishi Vidyapeeth', 'India', '{}', 'UGC'),
  ('Krantiguru Shyamji Krishna Verma Kachchh University', 'India', '{}', 'UGC'),
  ('Krishna Institute of Medical Sciences', 'India', '{}', 'UGC'),
  ('Krishna Kanta Handique State Open University', 'India', '{}', 'UGC'),
  ('Krishna University', 'India', '{}', 'UGC'),
  ('Krishnaguru Adhyatmik Visvavidyalaya', 'India', '{}', 'UGC'),
  ('Krishnakumarsinhji Bhavnagar University', 'India', '{}', 'UGC'),
  ('Kumar Bhaskar Varma Sanskrit & Ancient Studies University', 'India', '{}', 'UGC'),
  ('Kumaraguru College of Technology', 'India', '{}', 'UGC'),
  ('Kumaun University', 'India', '{}', 'UGC'),
  ('Kurukshetra University', 'India', '{}', 'UGC'),
  ('Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Kuvempu University', 'India', '{}', 'UGC'),
  ('L.D.College of Engineering', 'India', '{}', 'UGC'),
  ('LNCT University', 'India', '{}', 'UGC'),
  ('Lakshmibai National Institute of Physical Education', 'India', '{}', 'UGC'),
  ('Lakulish Yoga University', 'India', '{}', 'UGC'),
  ('Lala Lajpat Rai University of Veterinary & Animal Sciences', 'India', '{}', 'UGC'),
  ('Lalit Narayan Mithila University', 'India', '{}', 'UGC'),
  ('Lingaya''s Vidyapeeth', 'India', '{}', 'UGC'),
  ('Lords University', 'India', '{}', 'UGC'),
  ('Lovely Professional University', 'India', '{}', 'UGC'),
  ('Loyola-ICAM College of Engineering and Technology', 'India', '{}', 'UGC'),
  ('Lucknow University', 'India', '{}', 'UGC'),
  ('M.J.P. Rohilkhand University', 'India', '{}', 'UGC'),
  ('M.P.Bhoj (open) University', 'India', '{}', 'UGC'),
  ('M.S. Ramaiah University of Applied Sciences', 'India', '{}', 'UGC'),
  ('M.V.N. University', 'India', '{}', 'UGC'),
  ('MATS University', 'India', '{}', 'UGC'),
  ('MGM Institute of Health Sciences', 'India', '{}', 'UGC'),
  ('MIT Art Design and Technology University', 'India', '{}', 'UGC'),
  ('MIT World Peace University', 'India', '{}', 'UGC'),
  ('Madan Mohan Malaviya University of Technology', 'India', '{}', 'UGC'),
  ('Madaras University', 'India', '{}', 'UGC'),
  ('Madhav University', 'India', '{}', 'UGC'),
  ('Madhya Pradesh Bhoj (Open) University', 'India', '{}', 'UGC'),
  ('Madhya Pradesh Pashu Chikitsa Vigyan Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Madhyanchal Professional University', 'India', '{}', 'UGC'),
  ('Madras Institute of Technology', 'India', '{}', 'UGC'),
  ('Madurai Kamaraj University', 'India', '{}', 'UGC'),
  ('Madurai Kamraj University', 'India', '{}', 'UGC'),
  ('Magadh University', 'India', '{}', 'UGC'),
  ('Mahamaya Technical University', 'India', '{}', 'UGC'),
  ('Mahapurusha Srimanta Sankaradeva Viswavidyalaya', 'India', '{}', 'UGC'),
  ('Maharahtra University of Health Sciences', 'India', '{}', 'UGC'),
  ('Maharaj Vinayak Global University', 'India', '{}', 'UGC'),
  ('Maharaja Agrasen University', 'India', '{}', 'UGC'),
  ('Maharaja Bir Bikram University', 'India', '{}', 'UGC'),
  ('Maharaja Chhatrasal Bundelkhand Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Maharaja Ganga Singh University', 'India', '{}', 'UGC'),
  ('Maharaja Ganga Singh University, Bikaner', 'India', '{}', 'UGC'),
  ('Maharaja Ranjit Singh Punjab Technical University', 'India', '{}', 'UGC'),
  ('Maharaja Sayajirao University of Baroda', 'India', '{}', 'UGC'),
  ('Maharaja Surajmal Brij University', 'India', '{}', 'UGC'),
  ('Maharana Partap Horticultural University', 'India', '{}', 'UGC'),
  ('Maharana Pratap University of Agriculture & Technology', 'India', '{}', 'UGC'),
  ('Maharashtra Animal & Fishery Sciences University', 'India', '{}', 'UGC'),
  ('Maharashtra National Law University', 'India', '{}', 'UGC'),
  ('Maharishi Arvind University Jaipur', 'India', '{}', 'UGC'),
  ('Maharishi Balmiki Sanskrit University', 'India', '{}', 'UGC'),
  ('Maharishi Dayanand Saraswati University', 'India', '{}', 'UGC'),
  ('Maharishi Dayanand University', 'India', '{}', 'UGC'),
  ('Maharishi Dayanand University, Rohtak', 'India', '{}', 'UGC'),
  ('Maharishi Mahesh Yogi Vedic Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Maharishi Markandeshwar (Deemed to be University)', 'India', '{}', 'UGC'),
  ('Maharishi Markandeshwar University', 'India', '{}', 'UGC'),
  ('Maharishi University of Information Technology', 'India', '{}', 'UGC'),
  ('Maharishi University of Management and Technology', 'India', '{}', 'UGC'),
  ('Maharshi Dayanand Sarswati University Ajmer', 'India', '{}', 'UGC'),
  ('Maharshi Panini Sanskrit Evam Vedic Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Mahatam Gandhi Kashi Vidyapeeth', 'India', '{}', 'UGC'),
  ('Mahatama Gandhi University', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi Central University', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi Chitrakut Gramoday University', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi Kashi Vidyapith', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi University', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi University of Medical Sciences & Technology', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi University, Kerala', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi University, Nalgonda', 'India', '{}', 'UGC'),
  ('Mahatma Gandhi Unversity', 'India', '{}', 'UGC'),
  ('Mahatma Jyoti Rao Phoole University', 'India', '{}', 'UGC'),
  ('Mahatma Jyotiba Phule Rohilkhand University Bareilly', 'India', '{}', 'UGC'),
  ('Mahatma Phule Agricultural University', 'India', '{}', 'UGC'),
  ('Mahatma Phule Krishi Vidyapeeth', 'India', '{}', 'UGC'),
  ('Makanlal Chutur Vedi University', 'India', '{}', 'UGC'),
  ('Makhanlal Chaturvedi National University of Journalism & Communication', 'India', '{}', 'UGC'),
  ('Malaviya National Institute of Technology Jaipur', 'India', '{}', 'UGC'),
  ('Malviya National Institute of Technology', 'India', '{}', 'UGC'),
  ('Malwanchal University', 'India', '{}', 'UGC'),
  ('Manav Bharti University', 'India', '{}', 'UGC'),
  ('Manav Rachna International Institute of Research and Studies', 'India', '{}', 'UGC'),
  ('Manav Rachna University', 'India', '{}', 'UGC'),
  ('Mandsaur University', 'India', '{}', 'UGC'),
  ('Mangalayatan University', 'India', '{}', 'UGC'),
  ('Mangalore University', 'India', '{}', 'UGC'),
  ('Manipal University', 'India', '{}', 'UGC'),
  ('Manipur International University', 'India', '{}', 'UGC'),
  ('Manipur Technical University', 'India', '{}', 'UGC'),
  ('Manipur University', 'India', '{}', 'UGC'),
  ('Manipur University of Culture', 'India', '{}', 'UGC'),
  ('Manonmaniam Sundarnar University', 'India', '{}', 'UGC'),
  ('Mansarovar Global University', 'India', '{}', 'UGC'),
  ('Mar Athanasios College for Advanced Studies', 'India', '{}', 'UGC'),
  ('Marathwada Agricultural University', 'India', '{}', 'UGC'),
  ('Martin Luther Christian University', 'India', '{}', 'UGC'),
  ('Marwadi University', 'India', '{}', 'UGC'),
  ('Mata Gujri University', 'India', '{}', 'UGC'),
  ('Maulana Abul Kalam Azad University of Technology', 'India', '{}', 'UGC'),
  ('Maulana Azad National Institute of Technology', 'India', '{}', 'UGC'),
  ('Maulana Azad National Institute of Technology Bhopal', 'India', '{}', 'UGC'),
  ('Maulana Azad National Urdu University', 'India', '{}', 'UGC'),
  ('Maulana Azad University', 'India', '{}', 'UGC'),
  ('Maulana Mazharul Haque Arabic & Persian University', 'India', '{}', 'UGC'),
  ('Medi-Caps University', 'India', '{}', 'UGC'),
  ('Meenakshi Academy of Higher Education and Research', 'India', '{}', 'UGC'),
  ('Mewar University', 'India', '{}', 'UGC'),
  ('Mizoram University', 'India', '{}', 'UGC'),
  ('Mody Institute of Education and Research', 'India', '{}', 'UGC'),
  ('Mody University of Science & Technology', 'India', '{}', 'UGC'),
  ('Mohammad Ali Jauhar University', 'India', '{}', 'UGC'),
  ('Mohan Lal Shukhadia University', 'India', '{}', 'UGC'),
  ('Mohan Lal Sukhadia University', 'India', '{}', 'UGC'),
  ('Monad University', 'India', '{}', 'UGC'),
  ('Mother Teresa Women''s University', 'India', '{}', 'UGC'),
  ('Motherhood University', 'India', '{}', 'UGC'),
  ('Motilal Nehru National Institute Of Technology', 'India', '{}', 'UGC'),
  ('Motilal Nehru National Institute of Technolgy', 'India', '{}', 'UGC'),
  ('Moulana Azad national Urdu University', 'India', '{}', 'UGC'),
  ('Mumbai University', 'India', '{}', 'UGC'),
  ('Munger University', 'India', '{}', 'UGC'),
  ('Mysore University', 'India', '{}', 'UGC'),
  ('NIILM University', 'India', '{}', 'UGC'),
  ('NIIT University', 'India', '{}', 'UGC'),
  ('NIMS University', 'India', '{}', 'UGC'),
  ('Nagaland University', 'India', '{}', 'UGC'),
  ('Nagpur University', 'India', '{}', 'UGC'),
  ('Nalanda Open University', 'India', '{}', 'UGC'),
  ('Nalanda University', 'India', '{}', 'UGC'),
  ('Narendra Deo University of Agriculture & Technology', 'India', '{}', 'UGC'),
  ('Narendra Deva University of Agriculture and Technology', 'India', '{}', 'UGC'),
  ('Narsee Monjee Institute of Management Studies', 'India', '{}', 'UGC'),
  ('Narula Institute of Technology', 'India', '{}', 'UGC'),
  ('National Academy of Legal Studies & Research University', 'India', '{}', 'UGC'),
  ('National Brain Research Centre', 'India', '{}', 'UGC'),
  ('National Dairy Research Institute', 'India', '{}', 'UGC'),
  ('National Insitute of Technology', 'India', '{}', 'UGC'),
  ('National Institute of Food Technology Entrepreneurship & Management (NIFTEM)', 'India', '{}', 'UGC'),
  ('National Institute of Industrial Engineering', 'India', '{}', 'UGC'),
  ('National Institute of Mental Health and Neuro Sciences', 'India', '{}', 'UGC'),
  ('National Institute of Pharmeutical Education & Research', 'India', '{}', 'UGC'),
  ('National Institute of Technology Agartala', 'India', '{}', 'UGC'),
  ('National Institute of Technology Andhra Pradesh', 'India', '{}', 'UGC'),
  ('National Institute of Technology Arunachal Pradesh', 'India', '{}', 'UGC'),
  ('National Institute of Technology Calicut', 'India', '{}', 'UGC'),
  ('National Institute of Technology Delhi', 'India', '{}', 'UGC'),
  ('National Institute of Technology Durgapur', 'India', '{}', 'UGC'),
  ('National Institute of Technology Goa', 'India', '{}', 'UGC'),
  ('National Institute of Technology Hamirpur', 'India', '{}', 'UGC'),
  ('National Institute of Technology Jamshedpur', 'India', '{}', 'UGC'),
  ('National Institute of Technology Karnataka', 'India', '{}', 'UGC'),
  ('National Institute of Technology Kurukshetra', 'India', '{}', 'UGC'),
  ('National Institute of Technology Manipur', 'India', '{}', 'UGC'),
  ('National Institute of Technology Meghalaya', 'India', '{}', 'UGC'),
  ('National Institute of Technology Mizoram', 'India', '{}', 'UGC'),
  ('National Institute of Technology Nagaland', 'India', '{}', 'UGC'),
  ('National Institute of Technology Patna', 'India', '{}', 'UGC'),
  ('National Institute of Technology Puducherry', 'India', '{}', 'UGC'),
  ('National Institute of Technology Raipur', 'India', '{}', 'UGC'),
  ('National Institute of Technology Rourkela', 'India', '{}', 'UGC'),
  ('National Institute of Technology Sikkim', 'India', '{}', 'UGC'),
  ('National Institute of Technology Silchar', 'India', '{}', 'UGC'),
  ('National Institute of Technology Srinagar', 'India', '{}', 'UGC'),
  ('National Institute of Technology Surathkal', 'India', '{}', 'UGC'),
  ('National Institute of Technology Trichy', 'India', '{}', 'UGC'),
  ('National Institute of Technology Uttarakhand', 'India', '{}', 'UGC'),
  ('National Law Institute University', 'India', '{}', 'UGC'),
  ('National Law School of India University', 'India', '{}', 'UGC'),
  ('National Law Universituy', 'India', '{}', 'UGC'),
  ('National Law University', 'India', '{}', 'UGC'),
  ('National Law University and Judicial Academy', 'India', '{}', 'UGC'),
  ('National Museum Institute of History of Arts Conservation and Musicology', 'India', '{}', 'UGC'),
  ('National Rail and Transportation Institute', 'India', '{}', 'UGC'),
  ('National Sanskrit University', 'India', '{}', 'UGC'),
  ('National Sports University', 'India', '{}', 'UGC'),
  ('National University of Advanced Legal Studies (NUALS)', 'India', '{}', 'UGC'),
  ('National University of Educational Planning & Administration', 'India', '{}', 'UGC'),
  ('National University of Study & Research in Law', 'India', '{}', 'UGC'),
  ('Nava Nalanda Mahavihara', 'India', '{}', 'UGC'),
  ('Navrachana University', 'India', '{}', 'UGC'),
  ('Navsari Agriculture University', 'India', '{}', 'UGC'),
  ('Nehru Gram Bharati', 'India', '{}', 'UGC'),
  ('Netaji Shubhash Open University', 'India', '{}', 'UGC'),
  ('Netaji Subhas University', 'India', '{}', 'UGC'),
  ('Nilamber-Pitamber University', 'India', '{}', 'UGC'),
  ('Nirma University', 'India', '{}', 'UGC'),
  ('Nitte', 'India', '{}', 'UGC'),
  ('Nizam''s Institute of Medical Sciences', 'India', '{}', 'UGC'),
  ('Noida International University', 'India', '{}', 'UGC'),
  ('Noorul Islam Centre for Higher Education', 'India', '{}', 'UGC'),
  ('North Benagal University', 'India', '{}', 'UGC'),
  ('North East Frontier Technical University', 'India', '{}', 'UGC'),
  ('North Eastern Hill University', 'India', '{}', 'UGC'),
  ('North Eastern Regional Institute of Science & Technology', 'India', '{}', 'UGC'),
  ('North Maharashtra University', 'India', '{}', 'UGC'),
  ('North Orissa University', 'India', '{}', 'UGC'),
  ('NorthCap University', 'India', '{}', 'UGC'),
  ('O.P. Jindal University', 'India', '{}', 'UGC'),
  ('OPJS University', 'India', '{}', 'UGC'),
  ('Odisha State Open University', 'India', '{}', 'UGC'),
  ('Om Sterling Global University', 'India', '{}', 'UGC'),
  ('Open International University for Alternative Medicines', 'India', '{}', 'UGC'),
  ('Oriental University', 'India', '{}', 'UGC'),
  ('Orissa University of Agriculture and Technology', 'India', '{}', 'UGC'),
  ('Osmania University', 'India', '{}', 'UGC'),
  ('P. P. Savani University', 'India', '{}', 'UGC'),
  ('P. V. Narasimha Rao Telangana Veterinary University', 'India', '{}', 'UGC'),
  ('P.K. University', 'India', '{}', 'UGC'),
  ('PDM University', 'India', '{}', 'UGC'),
  ('PES University', 'India', '{}', 'UGC'),
  ('PSG College of Technology', 'India', '{}', 'UGC'),
  ('Pacific Academy of Higher Education & Research (PAHER)', 'India', '{}', 'UGC'),
  ('Pacific Medical University', 'India', '{}', 'UGC'),
  ('Padmashree Dr.D.Y. Patil Vidyapeeeth', 'India', '{}', 'UGC'),
  ('Palamuru University', 'India', '{}', 'UGC'),
  ('Pandit Deendayal Energy University', 'India', '{}', 'UGC'),
  ('Pandit Deendayal petroleum University', 'India', '{}', 'UGC'),
  ('Pandit Dwarka Prasad Mishra Indian Institute of Information Technology', 'India', '{}', 'UGC'),
  ('Pandit Ravi Shankar Shukla University', 'India', '{}', 'UGC'),
  ('Pandit S N Shukla University', 'India', '{}', 'UGC'),
  ('Panimalar Engineering College', 'India', '{}', 'UGC'),
  ('Panjab University', 'India', '{}', 'UGC'),
  ('Parul University', 'India', '{}', 'UGC'),
  ('Patliputra University', 'India', '{}', 'UGC'),
  ('Patna University', 'India', '{}', 'UGC'),
  ('People''s University', 'India', '{}', 'UGC'),
  ('Periyar Manaimmai Institute of Science & Technology (PMIST)', 'India', '{}', 'UGC'),
  ('Periyar University', 'India', '{}', 'UGC'),
  ('Plastindia International University', 'India', '{}', 'UGC'),
  ('Pondicherry University', 'India', '{}', 'UGC'),
  ('Ponnaiyan Ramajayam Institute of Science & technology (PMIST)', 'India', '{}', 'UGC'),
  ('Poornima University', 'India', '{}', 'UGC'),
  ('Post-Graduate Institute of Medical Education & Research', 'India', '{}', 'UGC'),
  ('Postgraduate lnstitute of Medical Education and Research', 'India', '{}', 'UGC'),
  ('Potti Sreeramulu Telugu University', 'India', '{}', 'UGC'),
  ('Potti Sreeramulu Teugu Universtity', 'India', '{}', 'UGC'),
  ('Pragyan International University', 'India', '{}', 'UGC'),
  ('Pratap University', 'India', '{}', 'UGC'),
  ('Prathyusha Engineering College', 'India', '{}', 'UGC'),
  ('Pravara Institute of Medical Sciences', 'India', '{}', 'UGC'),
  ('Presidency University', 'India', '{}', 'UGC'),
  ('Professor Jayashankar Telangana State Agricultural University', 'India', '{}', 'UGC'),
  ('Pt. Bhagwat Dayal Sharma University of Health Sciences', 'India', '{}', 'UGC'),
  ('Pt. Sundarlal Sharma (Open) University', 'India', '{}', 'UGC'),
  ('Pt.Ravishankar Shukla University', 'India', '{}', 'UGC'),
  ('Punjab Agricultural University', 'India', '{}', 'UGC'),
  ('Punjab Agriculture University', 'India', '{}', 'UGC'),
  ('Punjab Engineering College', 'India', '{}', 'UGC'),
  ('Punjab Technical University', 'India', '{}', 'UGC'),
  ('Punjab University', 'India', '{}', 'UGC'),
  ('Punjabi University', 'India', '{}', 'UGC'),
  ('Punjabi University Patiala', 'India', '{}', 'UGC'),
  ('Purnea University', 'India', '{}', 'UGC'),
  ('Quantum University', 'India', '{}', 'UGC'),
  ('R.N.B. Global University', 'India', '{}', 'UGC'),
  ('RIMT University', 'India', '{}', 'UGC'),
  ('RK University', 'India', '{}', 'UGC'),
  ('RKDF University', 'India', '{}', 'UGC'),
  ('RMD Engineering College', 'India', '{}', 'UGC'),
  ('RMK College of Engineering and Technology', 'India', '{}', 'UGC'),
  ('RMK Engineering College', 'India', '{}', 'UGC'),
  ('Rabindra Bharati University', 'India', '{}', 'UGC'),
  ('Rabindranath Tagore University (formerly known as AISECT University)', 'India', '{}', 'UGC'),
  ('Radha Govind University', 'India', '{}', 'UGC'),
  ('Raffles University', 'India', '{}', 'UGC'),
  ('Rai Technology University', 'India', '{}', 'UGC'),
  ('Rai University', 'India', '{}', 'UGC'),
  ('Raiganj University', 'India', '{}', 'UGC'),
  ('Raj Rishi Bhartrihari Matsya University', 'India', '{}', 'UGC'),
  ('Raja Mansingh Tomar Music & Arts University', 'India', '{}', 'UGC'),
  ('Rajagiri School of Engineering and Technology', 'India', '{}', 'UGC'),
  ('Rajalakshmi Engineering College', 'India', '{}', 'UGC'),
  ('Rajalakshmi Institute of Technology', 'India', '{}', 'UGC'),
  ('Rajasthan Agricultural University, Bikaner', 'India', '{}', 'UGC'),
  ('Rajasthan Ayurveda University', 'India', '{}', 'UGC'),
  ('Rajasthan ILD Skills University (RISU)', 'India', '{}', 'UGC'),
  ('Rajasthan Technical University', 'India', '{}', 'UGC'),
  ('Rajasthan University', 'India', '{}', 'UGC'),
  ('Rajasthan University of Health Sciences', 'India', '{}', 'UGC'),
  ('Rajasthan University of Veterinary & Animal Sciences', 'India', '{}', 'UGC'),
  ('Rajasthan Vidyapeeth University', 'India', '{}', 'UGC'),
  ('Rajendra Agricultural University', 'India', '{}', 'UGC'),
  ('Rajitlal Institute of Technology & Health Sciences (RITHS)', 'India', '{}', 'UGC'),
  ('Rajiv Gandhi National Aviation University', 'India', '{}', 'UGC'),
  ('Rajiv Gandhi National Institute of Youth Development', 'India', '{}', 'UGC'),
  ('Rajiv Gandhi Prodoyogiki Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Rajiv Gandhi Technical University (University of Technology of Madhya Pradesh)', 'India', '{}', 'UGC'),
  ('Rajiv Gandhi University', 'India', '{}', 'UGC'),
  ('Rajiv Gandhi University of Health Science', 'India', '{}', 'UGC'),
  ('Rajiv Gandhi University of Knowledge Technology', 'India', '{}', 'UGC'),
  ('Rajmata Vijayaraje Scindia Krishi Vishwa Vidyalaya', 'India', '{}', 'UGC'),
  ('Raksha Shakti University', 'India', '{}', 'UGC'),
  ('Ram Krishna Dharmath Foundation University', 'India', '{}', 'UGC'),
  ('Rama Devi Women''s University', 'India', '{}', 'UGC'),
  ('Rama University', 'India', '{}', 'UGC'),
  ('Ramaiah University of Applied Sciences', 'India', '{}', 'UGC'),
  ('Ramakrishna Mission Vivekananda Educational and Research Institute', 'India', '{}', 'UGC'),
  ('Ramchandra Chandravansi University', 'India', '{}', 'UGC'),
  ('Ranchi University', 'India', '{}', 'UGC'),
  ('Rani Channamma University', 'India', '{}', 'UGC'),
  ('Rani Durgavati University', 'India', '{}', 'UGC'),
  ('Rani Durgavati Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Ras Bihari Bose Subharti university', 'India', '{}', 'UGC'),
  ('Rashtriya Sanskrit Sansthana', 'India', '{}', 'UGC'),
  ('Rashtriya Sanskrit Vidyapeeth', 'India', '{}', 'UGC'),
  ('Ravenshaw University', 'India', '{}', 'UGC'),
  ('Rayalaseema University', 'India', '{}', 'UGC'),
  ('Rayat Bahra University', 'India', '{}', 'UGC'),
  ('Renaissance University', 'India', '{}', 'UGC'),
  ('Reva University', 'India', '{}', 'UGC'),
  ('S.R.M Institute of Science and Technology', 'India', '{}', 'UGC'),
  ('SA Engineering College', 'India', '{}', 'UGC'),
  ('SASTRA University', 'India', '{}', 'UGC'),
  ('SMK Fomra Institute of Technology', 'India', '{}', 'UGC'),
  ('SRM University', 'India', '{}', 'UGC'),
  ('Sage University', 'India', '{}', 'UGC'),
  ('Sai Nath University', 'India', '{}', 'UGC'),
  ('Sai Tirupati University', 'India', '{}', 'UGC'),
  ('Sam Higginbottom Institute of Agriculture Technology & Sciences', 'India', '{}', 'UGC'),
  ('Sambalpur University', 'India', '{}', 'UGC'),
  ('Sampurnanand Sanskrit University', 'India', '{}', 'UGC'),
  ('Sampurnanand Sanskrit Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Sanchi University of Buddhist-Indic Studies', 'India', '{}', 'UGC'),
  ('Sandip University', 'India', '{}', 'UGC'),
  ('Sangai International University', 'India', '{}', 'UGC'),
  ('Sangam University', 'India', '{}', 'UGC'),
  ('Sanjay Gandhi Postgraduate lnstitute of Medical Sciences', 'India', '{}', 'UGC'),
  ('Sanjay Ghodawat University', 'India', '{}', 'UGC'),
  ('Sankalchand Patel University', 'India', '{}', 'UGC'),
  ('Sanskriti University', 'India', '{}', 'UGC'),
  ('Sant Baba Bhag Singh University', 'India', '{}', 'UGC'),
  ('Sant Gadge Baba Amravati University', 'India', '{}', 'UGC'),
  ('Sant Longowal Institute of Engineering and Technology', 'India', '{}', 'UGC'),
  ('Santosh', 'India', '{}', 'UGC'),
  ('Sardar Bhagwan Singh University', 'India', '{}', 'UGC'),
  ('Sardar Krushinagar Dantiwada Agricultural University', 'India', '{}', 'UGC'),
  ('Sardar Patel University', 'India', '{}', 'UGC'),
  ('Sardar Patel University of Police Security & Criminal Justice', 'India', '{}', 'UGC'),
  ('Sardar Valabh Bhai National Institute of Technology', 'India', '{}', 'UGC'),
  ('Sardar Vallabh Bhai Patel University of Agriculture & Technology', 'India', '{}', 'UGC'),
  ('Sardar Vallabhai Patel University of Agriculture Amd Technology', 'India', '{}', 'UGC'),
  ('Sardar Vallabhbhai National Institute of Technology', 'India', '{}', 'UGC'),
  ('Sardarkrushinagar Dantiwada Agricultural University', 'India', '{}', 'UGC'),
  ('Sarguja University', 'India', '{}', 'UGC'),
  ('Sarla Birla University', 'India', '{}', 'UGC'),
  ('Sarvepalli Radhakrishnan University', 'India', '{}', 'UGC'),
  ('Satavahana University', 'India', '{}', 'UGC'),
  ('Sathyabama Institute of Science and Technology', 'India', '{}', 'UGC'),
  ('Sathyabama University', 'India', '{}', 'UGC'),
  ('Saurashtra University', 'India', '{}', 'UGC'),
  ('Saveetha Amaravati University', 'India', '{}', 'UGC'),
  ('Saveetha Engineering College', 'India', '{}', 'UGC'),
  ('Saveetha Institute of Medical and Technical Sciences', 'India', '{}', 'UGC'),
  ('Saveetha School of Engineering', 'India', '{}', 'UGC'),
  ('Saveetha University', 'India', '{}', 'UGC'),
  ('Savitribai Phule Pune University', 'India', '{}', 'UGC'),
  ('School of Planning and Architecture', 'India', '{}', 'UGC'),
  ('Seacom Skills University', 'India', '{}', 'UGC'),
  ('Shanmugha Arts Science Technology & Research Academy (SASTRA)', 'India', '{}', 'UGC'),
  ('Sharda University', 'India', '{}', 'UGC'),
  ('Sharnbasva University', 'India', '{}', 'UGC'),
  ('Shekhawati University', 'India', '{}', 'UGC'),
  ('Sher-E-Kashmir University of Agricultural Sciences and Technology', 'India', '{}', 'UGC'),
  ('Sher-e-Kashmir University of Agricultural Science & Technology', 'India', '{}', 'UGC'),
  ('Shivaji University', 'India', '{}', 'UGC'),
  ('Shobhit Institute of Engineering & Technology', 'India', '{}', 'UGC'),
  ('Shobhit University', 'India', '{}', 'UGC'),
  ('Shobhit University, Meerut', 'India', '{}', 'UGC'),
  ('Shoolini University of Biotechnology and Management Sciences', 'India', '{}', 'UGC'),
  ('Shree Guru Gobind Singh Tricentenary University', 'India', '{}', 'UGC'),
  ('Shree Sankaracharaya University of Sanskrit', 'India', '{}', 'UGC'),
  ('Shree Somnath Sanskrit University', 'India', '{}', 'UGC'),
  ('Shreemati Nathibai Damodar Thackersey Women''s University', 'India', '{}', 'UGC'),
  ('Shri Dharmasthala Manjunatheshwara University', 'India', '{}', 'UGC'),
  ('Shri Govind Guru University', 'India', '{}', 'UGC'),
  ('Shri Guru Ram Rai University', 'India', '{}', 'UGC'),
  ('Shri Jagannath Sanskrit University', 'India', '{}', 'UGC'),
  ('Shri Jagannath Sanskrit Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Shri Jagdish Prasad Jhabarmal Tibrewala University', 'India', '{}', 'UGC'),
  ('Shri Jagdishprasad Jhabarmal Tibrewala University', 'India', '{}', 'UGC'),
  ('Shri Khushal Das University', 'India', '{}', 'UGC'),
  ('Shri Krishna University', 'India', '{}', 'UGC'),
  ('Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha', 'India', '{}', 'UGC'),
  ('Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapith', 'India', '{}', 'UGC'),
  ('Shri Mata Vaishno Devi University', 'India', '{}', 'UGC'),
  ('Shri Ramasamy Memorial University Sikkim', 'India', '{}', 'UGC'),
  ('Shri Ramswaroop Memorial University', 'India', '{}', 'UGC'),
  ('Shri Rawatpura Sarkar University', 'India', '{}', 'UGC'),
  ('Shri Vaishnav Vidyapeeth Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Shri Venkateshwara University', 'India', '{}', 'UGC'),
  ('Shridhar University', 'India', '{}', 'UGC'),
  ('Shyam University', 'India', '{}', 'UGC'),
  ('Siddharth University', 'India', '{}', 'UGC'),
  ('Sidho-Kanho-Birsha University', 'India', '{}', 'UGC'),
  ('Sido Kanhu Murmu University', 'India', '{}', 'UGC'),
  ('Sido Kanhu University', 'India', '{}', 'UGC'),
  ('Sikha ''O'' Anushandhan University', 'India', '{}', 'UGC'),
  ('Sikkim Manipal University', 'India', '{}', 'UGC'),
  ('Sikkim Manipal University of Health, Medical and Technological Sciences', 'India', '{}', 'UGC'),
  ('Sikkim State University', 'India', '{}', 'UGC'),
  ('Sikkim University', 'India', '{}', 'UGC'),
  ('Siksha ''O'' Anusandhan', 'India', '{}', 'UGC'),
  ('Singhania University', 'India', '{}', 'UGC'),
  ('Sir Padmapat Singhania University', 'India', '{}', 'UGC'),
  ('Sister Nivedita University', 'India', '{}', 'UGC'),
  ('Smt. Nathibai Damodar Thackersey Women''s University', 'India', '{}', 'UGC'),
  ('Solapur University', 'India', '{}', 'UGC'),
  ('Somaiya Vidyavihar', 'India', '{}', 'UGC'),
  ('South Asian Universit y', 'India', '{}', 'UGC'),
  ('South Asian University', 'India', '{}', 'UGC'),
  ('South Gujarat University', 'India', '{}', 'UGC'),
  ('Spicer Adventist University', 'India', '{}', 'UGC'),
  ('Sree Chitra Tirunal Institute for Medical Sciences and Technology', 'India', '{}', 'UGC'),
  ('Sree Rama Krishna Degree College', 'India', '{}', 'UGC'),
  ('Sree Sankaracharya University of Sanskrit', 'India', '{}', 'UGC'),
  ('Sri Balaji Vidyapeeth (Deemed to be University)', 'India', '{}', 'UGC'),
  ('Sri Chandrasekharendra Saraswathi Vishwa Mahavidyalaya', 'India', '{}', 'UGC'),
  ('Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya', 'India', '{}', 'UGC'),
  ('Sri Dev Suman Uttarakhand Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Sri Devraj Urs Academy of Higher Education and Research', 'India', '{}', 'UGC'),
  ('Sri Guru Granth Sahib World University', 'India', '{}', 'UGC'),
  ('Sri Guru Ram Das University of Health Sciences', 'India', '{}', 'UGC'),
  ('Sri Konda Laxman Telangana State Horticultural University', 'India', '{}', 'UGC'),
  ('Sri Krishnadevaraya University', 'India', '{}', 'UGC'),
  ('Sri P V Narsimha Rao Telangana Veterinary University', 'India', '{}', 'UGC'),
  ('Sri Padmavati Mahila Vishwavidyalayam', 'India', '{}', 'UGC'),
  ('Sri Padmavati Women''s University', 'India', '{}', 'UGC'),
  ('Sri Ramachandra Medical College and Research Institute', 'India', '{}', 'UGC'),
  ('Sri Ramachardra Medical College and Research Institute', 'India', '{}', 'UGC'),
  ('Sri Sai Ram Engineering College', 'India', '{}', 'UGC'),
  ('Sri Sai Ram Institute of Technology', 'India', '{}', 'UGC'),
  ('Sri Sai University', 'India', '{}', 'UGC'),
  ('Sri Sant Gajanan Maharaj College of Engineering', 'India', '{}', 'UGC'),
  ('Sri Sathya Sai Institute of Higher Learning', 'India', '{}', 'UGC'),
  ('Sri Satya Sai University of Technology & Medical Sciences', 'India', '{}', 'UGC'),
  ('Sri Siddhartha Academy of Higher Education', 'India', '{}', 'UGC'),
  ('Sri Sivasubramaniya Nadar Institutions', 'India', '{}', 'UGC'),
  ('Sri Sri University', 'India', '{}', 'UGC'),
  ('Sri Venkateswara College of Engineering', 'India', '{}', 'UGC'),
  ('Sri Venkateswara Institute of Medical Sciences', 'India', '{}', 'UGC'),
  ('Sri Venkateswara University', 'India', '{}', 'UGC'),
  ('Sri Venkateswara Vedic University', 'India', '{}', 'UGC'),
  ('Sri Venkateswara Veterinary University', 'India', '{}', 'UGC'),
  ('Srimanta Sankaradeva University of Health Sciences', 'India', '{}', 'UGC'),
  ('Srinivas University', 'India', '{}', 'UGC'),
  ('St Joseph''s College Of Engineering', 'India', '{}', 'UGC'),
  ('St Joseph''s Institute Of Technology', 'India', '{}', 'UGC'),
  ('St. Joseph University', 'India', '{}', 'UGC'),
  ('St. Joseph''s College of Commerce', 'India', '{}', 'UGC'),
  ('St. Peter’s Institute of Higher Education and Research', 'India', '{}', 'UGC'),
  ('St. Xavier''s University', 'India', '{}', 'UGC'),
  ('Starex University', 'India', '{}', 'UGC'),
  ('State University of Performing and Visual Arts', 'India', '{}', 'UGC'),
  ('Sumandeep Vidyapeeth', 'India', '{}', 'UGC'),
  ('Sunrise University', 'India', '{}', 'UGC'),
  ('Suresh Gyan Vihar University', 'India', '{}', 'UGC'),
  ('Swami Keshwanand Rajasthan Agriculture University', 'India', '{}', 'UGC'),
  ('Swami Rama Himalayan University', 'India', '{}', 'UGC'),
  ('Swami Ramanand Teerth Marathwada University', 'India', '{}', 'UGC'),
  ('Swami Vivekanand University', 'India', '{}', 'UGC'),
  ('Swami Vivekananda Subharti University', 'India', '{}', 'UGC'),
  ('Swami Vivekananda Yoga Anusandhana Samsthana', 'India', '{}', 'UGC'),
  ('Swarnim Gujarat Sports University', 'India', '{}', 'UGC'),
  ('Swarnim Startup & Innovation University', 'India', '{}', 'UGC'),
  ('Symbiosis Skills and Open University', 'India', '{}', 'UGC'),
  ('Symbiosis University of Applied Sciences (SUAS)', 'India', '{}', 'UGC'),
  ('T.M. Bhagalpur University', 'India', '{}', 'UGC'),
  ('TERI School of Advanced studies', 'India', '{}', 'UGC'),
  ('Takhatmal Shrivallabh Homoeopathic Medical College', 'India', '{}', 'UGC'),
  ('Tamil Nadu Agricultural University', 'India', '{}', 'UGC'),
  ('Tamil Nadu Dr. Ambedkar Law University', 'India', '{}', 'UGC'),
  ('Tamil Nadu Dr. M.G.R. Medical University', 'India', '{}', 'UGC'),
  ('Tamil Nadu Fisheries University', 'India', '{}', 'UGC'),
  ('Tamil Nadu Music and Fine Arts University', 'India', '{}', 'UGC'),
  ('Tamil Nadu Open University', 'India', '{}', 'UGC'),
  ('Tamil Nadu Teacher Education University', 'India', '{}', 'UGC'),
  ('Tamil Nadu Veterinary and Animal Sciences University', 'India', '{}', 'UGC'),
  ('Tamil University', 'India', '{}', 'UGC'),
  ('Tamilnadu Agricultural University', 'India', '{}', 'UGC'),
  ('Tamilnadu Dr. Ambedkar Law University', 'India', '{}', 'UGC'),
  ('Tamilnadu Dr. M.G.R.Medical University', 'India', '{}', 'UGC'),
  ('Tamilnadu National Law School', 'India', '{}', 'UGC'),
  ('Tamilnadu Physical Educaton and Sports University', 'India', '{}', 'UGC'),
  ('Tamilnadu Veterinary & Animal Sciences University', 'India', '{}', 'UGC'),
  ('Tantia University', 'India', '{}', 'UGC'),
  ('Tata Institute of Fundamental Research', 'India', '{}', 'UGC'),
  ('Tata Institute of Social Sciences', 'India', '{}', 'UGC'),
  ('Team Lease Skills University', 'India', '{}', 'UGC'),
  ('Technique Polytechnic Institute', 'India', '{}', 'UGC'),
  ('Techno Global University', 'India', '{}', 'UGC'),
  ('Techno India University', 'India', '{}', 'UGC'),
  ('Teerthanker Mahaveer University', 'India', '{}', 'UGC'),
  ('Telangana University', 'India', '{}', 'UGC'),
  ('Tezpur University', 'India', '{}', 'UGC'),
  ('The Assam Kaziranga University', 'India', '{}', 'UGC'),
  ('The Assam Royal Global University', 'India', '{}', 'UGC'),
  ('The Bengal Engineering & Science University', 'India', '{}', 'UGC'),
  ('The Gandhiigram Rural Institute', 'India', '{}', 'UGC'),
  ('The Global Open University', 'India', '{}', 'UGC'),
  ('The Global University', 'India', '{}', 'UGC'),
  ('The Glocal University', 'India', '{}', 'UGC'),
  ('The ICFAI University', 'India', '{}', 'UGC'),
  ('The Indira Gandhi National Tribal University', 'India', '{}', 'UGC'),
  ('The Institute of Chartered Financial Analysts of India University', 'India', '{}', 'UGC'),
  ('The LNM Institute of Information Technology jaipur', 'India', '{}', 'UGC'),
  ('The Neotia University', 'India', '{}', 'UGC'),
  ('The New College', 'India', '{}', 'UGC'),
  ('The Northcap University', 'India', '{}', 'UGC'),
  ('The Rajiv Gandhi National University of Law', 'India', '{}', 'UGC'),
  ('The Rashtrasant Tukadoji Maharaj Nagpur University', 'India', '{}', 'UGC'),
  ('The Sanskrit College and University', 'India', '{}', 'UGC'),
  ('The West Bengal National University of Juridical Science', 'India', '{}', 'UGC'),
  ('The West Bengal University of Health Sciences', 'India', '{}', 'UGC'),
  ('Thiagarajar College of Engineering', 'India', '{}', 'UGC'),
  ('Thiruvalluvar University', 'India', '{}', 'UGC'),
  ('Thunchath Ezhuthachan Malayalam University', 'India', '{}', 'UGC'),
  ('Tilak Maharashtra Vidyapeeth', 'India', '{}', 'UGC'),
  ('Tilka Manjhi Bhagalpur University', 'India', '{}', 'UGC'),
  ('Tripura University', 'India', '{}', 'UGC'),
  ('Tumkur University', 'India', '{}', 'UGC'),
  ('U.P. Pandit Deen Dayal Upadhyaya Pashu Chikitsa Vigyan Vishwavidhyalaya Evam Go-Anusandhan Sansthan', 'India', '{}', 'UGC'),
  ('U.P. Rajarshi Tandon Open University', 'India', '{}', 'UGC'),
  ('U.P.King George''s University of Dental Sciences', 'India', '{}', 'UGC'),
  ('UKA Tarsadia University', 'India', '{}', 'UGC'),
  ('University College of Medical Sciences', 'India', '{}', 'UGC'),
  ('University College, Thiruvananthapuram', 'India', '{}', 'UGC'),
  ('University of Agricultural Sciences', 'India', '{}', 'UGC'),
  ('University of Agricultural Sciences, Bangalore', 'India', '{}', 'UGC'),
  ('University of Agricultural Sciences, Dharwad', 'India', '{}', 'UGC'),
  ('University of Allahabad', 'India', '{}', 'UGC'),
  ('University of Burdwan', 'India', '{}', 'UGC'),
  ('University of Calcutta', 'India', '{}', 'UGC'),
  ('University of Calicut', 'India', '{}', 'UGC'),
  ('University of Engineering and Management', 'India', '{}', 'UGC'),
  ('University of Health Sciences Andhra Pradesh', 'India', '{}', 'UGC'),
  ('University of Horticultural Sciences', 'India', '{}', 'UGC'),
  ('University of Hyderabad', 'India', '{}', 'UGC'),
  ('University of Jammu', 'India', '{}', 'UGC'),
  ('University of Kalyani', 'India', '{}', 'UGC'),
  ('University of Kashmir', 'India', '{}', 'UGC'),
  ('University of Kerala', 'India', '{}', 'UGC'),
  ('University of Kota', 'India', '{}', 'UGC'),
  ('University of Lucknow', 'India', '{}', 'UGC'),
  ('University of Madras', 'India', '{}', 'UGC'),
  ('University of Media Arts', 'India', '{}', 'UGC'),
  ('University of Music and Fine Arts', 'India', '{}', 'UGC'),
  ('University of Mysore', 'India', '{}', 'UGC'),
  ('University of North Bengal', 'India', '{}', 'UGC'),
  ('University of Patanjali', 'India', '{}', 'UGC'),
  ('University of Petroleum and Energy Studies', 'India', '{}', 'UGC'),
  ('University of Pune', 'India', '{}', 'UGC'),
  ('University of Rajasthan', 'India', '{}', 'UGC'),
  ('University of Roorkee', 'India', '{}', 'UGC'),
  ('University of Science & Technology Meghalaya', 'India', '{}', 'UGC'),
  ('University of Technology', 'India', '{}', 'UGC'),
  ('University of Technology & Management', 'India', '{}', 'UGC'),
  ('Univesity of Gour Banga', 'India', '{}', 'UGC'),
  ('Usha Martin University', 'India', '{}', 'UGC'),
  ('Utkal University', 'India', '{}', 'UGC'),
  ('Utkal University of Culture', 'India', '{}', 'UGC'),
  ('Uttar Banga Krishi Vishwavidyalaya', 'India', '{}', 'UGC'),
  ('Uttar Pradesh Technical University', 'India', '{}', 'UGC'),
  ('Uttar Pradesh University of Medical Sciences', 'India', '{}', 'UGC'),
  ('Uttarakhand Aawasiya Viswavidyalaya', 'India', '{}', 'UGC'),
  ('Uttarakhand Ayurved University', 'India', '{}', 'UGC'),
  ('Uttarakhand Open University', 'India', '{}', 'UGC'),
  ('Uttarakhand Sanskrit University', 'India', '{}', 'UGC'),
  ('Uttarakhand Technical University', 'India', '{}', 'UGC'),
  ('Uttaranchal University', 'India', '{}', 'UGC'),
  ('VBS Purvanchal University', 'India', '{}', 'UGC'),
  ('VELS Institute of Science Technology & Advanced Studies (VISTAS)', 'India', '{}', 'UGC'),
  ('VIT Bhopal', 'India', '{}', 'UGC'),
  ('VIT Bhopal University', 'India', '{}', 'UGC'),
  ('VIT-AP University', 'India', '{}', 'UGC'),
  ('Vardhaman Mahaveer Open University', 'India', '{}', 'UGC'),
  ('Vardhman Mahaveer Open University', 'India', '{}', 'UGC'),
  ('Veer Bahadur Singh Purvanchal University', 'India', '{}', 'UGC'),
  ('Veer Chandra Singh Garhwali Uttarakhand University of Horticulture & Forestry', 'India', '{}', 'UGC'),
  ('Veer Kunwar Singh University', 'India', '{}', 'UGC'),
  ('Veer Narmad South Gujarat University', 'India', '{}', 'UGC'),
  ('Veer Surendra Sai Institute of Medical Science and Research', 'India', '{}', 'UGC'),
  ('Veer Surendra Sai University of Technology', 'India', '{}', 'UGC'),
  ('Vel Tech Rangarajan Dr. Sagunthala R & D Institute of Science and Technology', 'India', '{}', 'UGC'),
  ('Velammal Engineering College', 'India', '{}', 'UGC'),
  ('Velammal Institute of Technology', 'India', '{}', 'UGC'),
  ('Venkateshwara Open University', 'India', '{}', 'UGC'),
  ('Vesveswaraiah Technological University', 'India', '{}', 'UGC'),
  ('Vidya Sagar University', 'India', '{}', 'UGC'),
  ('Vidyasagar University', 'India', '{}', 'UGC'),
  ('Vignan University', 'India', '{}', 'UGC'),
  ('Vignan''s Foundation for Science Technology and Research', 'India', '{}', 'UGC'),
  ('Vijayanagara Sri Krishnadevaraya University', 'India', '{}', 'UGC'),
  ('Vikram University', 'India', '{}', 'UGC'),
  ('Vikrama Simhapuri University', 'India', '{}', 'UGC'),
  ('Vinayaka Mission''s Research Foundation-Deemed University', 'India', '{}', 'UGC'),
  ('Vinayaka Missions Sikkim University', 'India', '{}', 'UGC'),
  ('Vinayaka Mission’s Research Foundation', 'India', '{}', 'UGC'),
  ('Vinoba Bhave University', 'India', '{}', 'UGC'),
  ('Vishwakarma University', 'India', '{}', 'UGC'),
  ('Visva Bharati', 'India', '{}', 'UGC'),
  ('Visva-Bharati University', 'India', '{}', 'UGC'),
  ('Visvesvaraya National Institute of Technology', 'India', '{}', 'UGC'),
  ('Visvesvaraya Technological University', 'India', '{}', 'UGC'),
  ('Vivekananda Global University', 'India', '{}', 'UGC'),
  ('West Bengal State University', 'India', '{}', 'UGC'),
  ('West Bengal University of Animal and Fishery Sciences', 'India', '{}', 'UGC'),
  ('West Bengal University of Teachers Training Education Planning and Administration', 'India', '{}', 'UGC'),
  ('West Bengal University of Technology', 'India', '{}', 'UGC'),
  ('William Carey University', 'India', '{}', 'UGC'),
  ('World University Of Design', 'India', '{}', 'UGC'),
  ('Xavier university', 'India', '{}', 'UGC'),
  ('YBN University', 'India', '{}', 'UGC'),
  ('YMCA University of Science & Technology', 'India', '{}', 'UGC'),
  ('Yashawantrao Chavan Maharashtra Open University', 'India', '{}', 'UGC'),
  ('Yashwant Rao Chavan Maharashtra Open University', 'India', '{}', 'UGC'),
  ('Yenepoya', 'India', '{}', 'UGC'),
  ('Yogi Vemana University', 'India', '{}', 'UGC')
ON CONFLICT (name) DO NOTHING;

-- ─── ref_academic_domains — 487 India domains (Hipo, lowercased) ───
INSERT INTO public.ref_academic_domains (domain) VALUES
  ('aaidu.org'),
  ('aau.ac.in'),
  ('aditya.ac.in'),
  ('adtu.in'),
  ('aecwb.edu.in'),
  ('ahduni.edu.in'),
  ('aiims.ac.in'),
  ('aisectuniversity.ac.in'),
  ('alagappauniversity.ac.in'),
  ('alldunivpio.org'),
  ('alphagroup.edu'),
  ('altmeduniversity.com'),
  ('altmedworld.net'),
  ('amity.edu'),
  ('amrita.edu'),
  ('amtuni.com'),
  ('amu.ac.in'),
  ('andhrauniversity.info'),
  ('angrau.net'),
  ('annamalaiuniversity.ac.in'),
  ('annauniv.edu'),
  ('annauniv.edu.in'),
  ('anurag.edu.in'),
  ('apsurewa.nic.in'),
  ('aryainstitutejpr.com'),
  ('ashoka.edu.in'),
  ('assamuniversity.nic.in'),
  ('atharvacoe.ac.in'),
  ('avinuty.ac.in'),
  ('ayurveduniversity.com'),
  ('bamu.net'),
  ('bamu.nic.in'),
  ('banasthali.org'),
  ('bankurauniv.com'),
  ('bau.nic.in'),
  ('bbauindia.org'),
  ('bckv.edu.in'),
  ('bdu.ernet.in'),
  ('becs.ac.in'),
  ('bengaluruuniversity.com'),
  ('bhagwantuniversity.com'),
  ('bharathi.ernet.in'),
  ('bharathuniv.com'),
  ('bharatividyapeeth.edu'),
  ('bhavuni.edu'),
  ('bhc.edu.in'),
  ('bhu.ac.in'),
  ('bicpu.edu.in'),
  ('bitmesraranchi.org'),
  ('bits-pilani.ac.in'),
  ('bnmu.in'),
  ('bpitindia.edu.in'),
  ('bpitindia.in'),
  ('bput.org'),
  ('brabu.net'),
  ('braou.ac.in'),
  ('brauagra.com'),
  ('bsauniv.ac.in'),
  ('bubhopal.nic.in'),
  ('bundelkhanduniversity.org'),
  ('burdwanuniversity.ac.in'),
  ('caluniv.ac.in'),
  ('cau.org.in'),
  ('ccsuniversity.ac.in'),
  ('ccsuniversity.org'),
  ('cesbm.ac.in'),
  ('chandilpolytechnic.org'),
  ('charusat.ac.in'),
  ('chitkara.edu.in'),
  ('chitkarauniversity.edu.in'),
  ('christuniversity.in'),
  ('ciefl.org'),
  ('cife.edu.in'),
  ('cihts.ac.in'),
  ('citchennai.edu.in'),
  ('cmjuniversity.edu.in'),
  ('coeptech.ac.in'),
  ('coer.ac.in'),
  ('coeruniversity.ac.in'),
  ('csauk.ac.in'),
  ('cusat.ac.in'),
  ('cvru.ac.in'),
  ('da-iict.org'),
  ('darulhuda.com'),
  ('davietjal.org'),
  ('davuniversity.org'),
  ('davv.ac.in'),
  ('dbatechuni.org'),
  ('dbskkv.org'),
  ('dceonline.net'),
  ('ddu.ac.in'),
  ('ddugu.edu.in'),
  ('deccancollegepune.ac.in'),
  ('dei.ac.in'),
  ('dibru.ernet.in'),
  ('dravidianuniversity.ac.in'),
  ('du.ac.in'),
  ('dypatiluniversity.org'),
  ('eiilmuniversity.ac.in'),
  ('fatimacollege.net'),
  ('fri.icfre.gov.in'),
  ('gbpuat.ac.in'),
  ('ggu.ac.in'),
  ('gipe.ernet.in'),
  ('gitam.edu'),
  ('gju.ernet.in'),
  ('gkcem.ac.in'),
  ('gkvharidwar.org'),
  ('gnduonline.org'),
  ('gnidsr.ac.in'),
  ('gnihm.ac.in'),
  ('gnipst.ac.in'),
  ('gnit.ac.in'),
  ('golapolytechnic.org'),
  ('government.ind.in'),
  ('gsfcuniversity.ac.in'),
  ('gtu.ac.in'),
  ('gu.nic.in'),
  ('gujaratuniversity.org.in'),
  ('gulbargauniversity.kar.nic.in'),
  ('gurukuluniversity.org'),
  ('hau.ernet.in'),
  ('hillagric.ernet.in'),
  ('hindustanuniv.ac.in'),
  ('hnbgu.ac.in'),
  ('hnluraipur.com'),
  ('hpuniv.nic.in'),
  ('iari.ernet.in'),
  ('iaseduniv.org'),
  ('icfai.org'),
  ('ifheindia.org'),
  ('igau.edu.in'),
  ('igidr.ac.in'),
  ('igims.org'),
  ('ignou.ac.in'),
  ('iiit-bh.ac.in'),
  ('iiita.com'),
  ('iiitb.ac.in'),
  ('iiitd.ac.in'),
  ('iiitg.ac.in'),
  ('iiitkota.ac.in'),
  ('iiitm.ac.in'),
  ('iiitmk.ac.in'),
  ('iiits.in'),
  ('iiitvadodara.ac.in'),
  ('iimtrichy.ac.in'),
  ('iipsindia.org'),
  ('iisc.ac.in'),
  ('iisc.ernet.in'),
  ('iitb.ac.in'),
  ('iitbbs.ac.in'),
  ('iitd.ac.in'),
  ('iitd.ernet.in'),
  ('iitg.ac.in'),
  ('iitg.ernet.in'),
  ('iitgn.ac.in'),
  ('iith.ac.in'),
  ('iiti.ac.in'),
  ('iitj.ac.in'),
  ('iitk.ac.in'),
  ('iitkgp.ac.in'),
  ('iitkgp.ernet.in'),
  ('iitm.ac.in'),
  ('iitp.ac.in'),
  ('iitr.ac.in'),
  ('iitrpr.ac.in'),
  ('iksvv.com'),
  ('ili.ac.in'),
  ('indusuni.ac.in'),
  ('integraluniversity.ac.in'),
  ('ipu.ac.in'),
  ('isbm.org.in'),
  ('isical.ac.in'),
  ('ismdhanbad.ac.in'),
  ('itmindia.edu'),
  ('iudehradun.edu.in'),
  ('iuhimachal.edu.in'),
  ('iujaipur.edu.in'),
  ('iujharkhand.edu.in'),
  ('iumeghalaya.edu.in'),
  ('iumizoram.edu.in'),
  ('iunagaland.edu.in'),
  ('iur.ac.in'),
  ('iuraipur.edu.in'),
  ('iusikkim.edu.in'),
  ('iutripura.edu.in'),
  ('ivri.nic.in'),
  ('jadavpur.edu'),
  ('jainuniversity.org'),
  ('jamiahamdard.edu'),
  ('jammuvarsity.org'),
  ('jeppiaarcollege.org'),
  ('jiit.ac.in'),
  ('jiscollege.ac.in'),
  ('jisiasr.org'),
  ('jisiop.org'),
  ('jismsr.org'),
  ('jissp.ac.in'),
  ('jisuniversity.ac.in'),
  ('jiwaji.edu'),
  ('jjtu.ac.in'),
  ('jmi.nic.in'),
  ('jncasr.ac.in'),
  ('jnkvv.nic.in'),
  ('jntuh.ac.in'),
  ('jnu.ac.in'),
  ('jnujaipur.ac.in'),
  ('jodhpurnationaluniversity.com'),
  ('jpv.bih.nic.in'),
  ('jrnrvu.org'),
  ('jvbi.ac.in'),
  ('kalingauniversity.com'),
  ('kanchiuniv.ac.in'),
  ('kannadauniversity.org'),
  ('kannuruniversity.ac.in'),
  ('kanpuruniversity.org'),
  ('karnatakastateopenuniversity.in'),
  ('karpagamuniv.com'),
  ('karunya.edu'),
  ('kashmiruniversity.net'),
  ('kau.edu'),
  ('kcgcollege.ac.in'),
  ('kct.ac.in'),
  ('keralauniversity.ac.in'),
  ('kiet.edu'),
  ('kiit.ac.in'),
  ('kimi.kohinoor.ac.in'),
  ('klyuniv.ac.in'),
  ('knruhs.telangana.gov.in'),
  ('krishnauniversity.ac.in'),
  ('ksdsu.edu.in'),
  ('kslu.ac.in'),
  ('kud.ac.in'),
  ('kufos.ac.in'),
  ('kukinfo.com'),
  ('kumaununiversity.org'),
  ('kuvempu.ac.in'),
  ('kuwarangal.com'),
  ('ldceahd.org'),
  ('licet.ac.in'),
  ('lnipe.edu'),
  ('lnmu.bih.nic.in'),
  ('lpu.in'),
  ('lucknowuniv.org'),
  ('macfast.org'),
  ('magadhuniversity.org'),
  ('manavrachna.edu.in'),
  ('mangaloreuniversity.ac.in'),
  ('manipal.edu'),
  ('manipuruniv.ac.in'),
  ('manit.ac.in'),
  ('manuu.ac.in'),
  ('mcu.ac.in'),
  ('mdsuajmer.ac.in'),
  ('mdurohtak.com'),
  ('mgkvp.ac.in'),
  ('mgsubikaner.ac.in'),
  ('mgu.ac.in'),
  ('mguniversity.ac.in'),
  ('mitindia.edu'),
  ('mitwpu.edu.in'),
  ('mjpru.ac.in'),
  ('mkuhyd.com'),
  ('mkv2.mah.nic.in'),
  ('mlsu.ac.in'),
  ('mnit.ac.in'),
  ('mnnit.ac.in'),
  ('mpbou.org'),
  ('mpkv.mah.nic.in'),
  ('msruas.ac.in'),
  ('msubaroda.ac.in'),
  ('mu.ac.in'),
  ('nagarjunauniversity.ac.in'),
  ('nagauniv.org.in'),
  ('nagpur-university.com'),
  ('nalandaopenuniversity.info'),
  ('nbu.ac.in'),
  ('ncuindia.edu'),
  ('ndri.nic.in'),
  ('nduat.nic.in'),
  ('nehu.ac.in'),
  ('ngu.ac.in'),
  ('nimhans.kar.nic.in'),
  ('nims.ap.nic.in'),
  ('nims.edu.in'),
  ('nims.net.in'),
  ('nirmauni.ac.in'),
  ('nit.ac.in'),
  ('nita.ac.in'),
  ('nitandhra.ac.in'),
  ('nitap.in'),
  ('nitc.ac.in'),
  ('nitdelhi.ac.in'),
  ('nitdgp.ac.in'),
  ('nitgoa.ac.in'),
  ('nith.ac.in'),
  ('nitie.edu'),
  ('nitj.ac.in'),
  ('nitjsr.ac.in'),
  ('nitk.ac.in'),
  ('nitk.edu.in'),
  ('nitkkr.net'),
  ('nitm.ac.in'),
  ('nitmanipur.ac.in'),
  ('nitmz.ac.in'),
  ('nitnagaland.ac.in'),
  ('nitp.ac.in'),
  ('nitpy.ac.in'),
  ('nitrkl.ac.in'),
  ('nitrr.ac.in'),
  ('nits.ac.in'),
  ('nitsikkim.ac.in'),
  ('nitsri.net'),
  ('nitt.edu'),
  ('nituk.ac.in'),
  ('nitw.ernet.in'),
  ('nls.ac.in'),
  ('nmims.edu'),
  ('nmu.ac.in'),
  ('nsut.ac.in'),
  ('ntruhs.ap.nic.in'),
  ('nuv.ac.in'),
  ('op.iitg.ac.in'),
  ('osmania.ac.in'),
  ('ouat.ac.in'),
  ('padmavatiwomen-univ.org'),
  ('palamuruuniversity.ac.in'),
  ('panimalar.ac.in'),
  ('panimalarengineeringcollegechennai.ac.in'),
  ('paruluniversity.ac.in'),
  ('pau.edu'),
  ('pdeu.ac.in'),
  ('pdkv.ac.in'),
  ('pdpu.ac.in'),
  ('pec.ac.in'),
  ('pes.edu'),
  ('pgimer.nic.in'),
  ('pjtau.edu.in'),
  ('pondiuni.org'),
  ('prathyusha.edu.in'),
  ('psgtech.edu'),
  ('ptetjnvu.org'),
  ('ptu.ac.in'),
  ('puchd.ac.in'),
  ('punjabiuniversity.ac.in'),
  ('puonline.bih.nic.in'),
  ('pusavarsity.org.in'),
  ('rabindrabharatiuniversity.net'),
  ('rajagiritech.edu.in'),
  ('rajalakshmi.org'),
  ('ranchiuniversity.org.in'),
  ('raubikaner.org'),
  ('rdunijbpin.org'),
  ('rgtu.net'),
  ('rgu.ac.in'),
  ('ritchennai.org'),
  ('riths.ac.in'),
  ('rmd.ac.in'),
  ('rmkcet.ac.in'),
  ('rmkec.ac.in'),
  ('rmlau.ac.in'),
  ('rnd.iitg.ac.in'),
  ('rsuniversity.com'),
  ('rtu.ac.in'),
  ('ruraluniversity-chitrakoot.org'),
  ('saec.ac.in'),
  ('sagaruniversity.nic.in'),
  ('sairam.edu.in'),
  ('sairamit.edu.in'),
  ('sambalpuruniversitypgc.in'),
  ('sanskrit.nic.in'),
  ('sastra.ac.in'),
  ('sastra.edu'),
  ('satavahana.ac.in'),
  ('sathyabamauniv.ac.in'),
  ('saurashtrauniversity.edu'),
  ('saveetha.ac.in'),
  ('saveetha.com'),
  ('saveethaengineering.com'),
  ('sctimst.ker.nic.in'),
  ('sdau.edu.in'),
  ('sgpgi.ac.in'),
  ('sgu.ernet.in'),
  ('sharda.ac.in'),
  ('shobhituniversity.ac.in'),
  ('shridharuniversity.ac.in'),
  ('simhapuriuniv.ac.in'),
  ('singhaniauniversity.ac.in'),
  ('siu.edu.in'),
  ('sjcc.edu.in'),
  ('sjsv.nic.in'),
  ('skltshu.ac.in'),
  ('skmu.edu.in'),
  ('skuastkashmir.ac.in'),
  ('skuniv.ap.nic.in'),
  ('slbsrsv.ac.in'),
  ('smkfomra.net'),
  ('smu.edu.in'),
  ('sndt.edu'),
  ('snuniv.ac.in'),
  ('soauniversity.ac.in'),
  ('somaiya.edu'),
  ('southasianuniversity.org'),
  ('spa.ac.in'),
  ('spuniv.org'),
  ('spuvvn.edu'),
  ('squareit.edu.in'),
  ('sriramachandra.edu.in'),
  ('srisathyasai.org.in'),
  ('srkdc.org'),
  ('srmap.edu.in'),
  ('srmeaswari.ac.in'),
  ('srmuniv.ac.in'),
  ('srtmun.org'),
  ('ssgmce.org'),
  ('ssn.edu.in'),
  ('ssus.ac.in'),
  ('ssvv.up.nic.in'),
  ('stjosephs.ac.in'),
  ('stjosephstechnology.ac.in'),
  ('su.digitaluniversity.ac'),
  ('surtech.edu.in'),
  ('svbpuctm.org'),
  ('svce.ac.in'),
  ('svimstpt.ap.nic.in'),
  ('svnit.ac.in'),
  ('svuni.ap.nic.in'),
  ('tamiluniversity.ac.in'),
  ('tanuvas.com'),
  ('tce.edu'),
  ('techniqueedu.com'),
  ('telanganauniversity.ac.in'),
  ('teluguuniversity.ac.in'),
  ('tezu.ernet.in'),
  ('thenewcollege.edu.in'),
  ('tiet.ac.in'),
  ('tiss.edu'),
  ('tmbu.org'),
  ('tmv.edu.in'),
  ('tnau.ac.in'),
  ('tndalu.org'),
  ('tnmmu.ac.in'),
  ('tripurauniv.in'),
  ('tshmc.org'),
  ('tsvu.nic.in'),
  ('tumkuruniversity.ac.in'),
  ('tvuni.in'),
  ('uasbng.kar.nic.in'),
  ('uasd.net'),
  ('uktech.ac.in'),
  ('uma.ac.in'),
  ('uni-mysore.ac.in'),
  ('unical.ac.in'),
  ('unigoa.ac.in'),
  ('unipune.ernet.in'),
  ('uniraj.org'),
  ('unishivaji.ac.in'),
  ('universitycollege.ac.in'),
  ('unom.ac.in'),
  ('uohyd.ernet.in'),
  ('uok.ac.in'),
  ('uor.org'),
  ('uou.ac.in'),
  ('upes.ac.in'),
  ('uptu.ac.in'),
  ('utkaluniv.org'),
  ('uumail.in'),
  ('vbspu.ac.in'),
  ('vbu.co.in'),
  ('velammal.edu.in'),
  ('velammalitech.edu.in'),
  ('vidyasagar.ac.in'),
  ('vignanuniversity.org'),
  ('vikramuniversity.org'),
  ('vinayakamissions.com'),
  ('visva-bharati.ac.in'),
  ('vit.ac.in'),
  ('vitbhopal.ac.in'),
  ('vksu-ara.org'),
  ('vmou.ac.in'),
  ('vnitnagpur.ac.in'),
  ('vssut.ac.in'),
  ('vtu.ac.in'),
  ('wbuafs.nic.in'),
  ('wbut.net'),
  ('ycmou.com'),
  ('ysparmaruniversity.org')
ON CONFLICT (domain) DO NOTHING;

-- ─── top-tier aliases — 50 institutions; ONLY where aliases is empty ───
UPDATE public.ref_universities SET aliases = ARRAY['NIT Calicut','NITC']
  WHERE name = 'National Institute of Technology Calicut' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NIT Rourkela','NITR']
  WHERE name = 'National Institute of Technology Rourkela' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['MNIT Jaipur','MNIT']
  WHERE name = 'Malaviya National Institute of Technology Jaipur' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['MANIT Bhopal','MANIT']
  WHERE name = 'Maulana Azad National Institute of Technology' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['MNNIT Allahabad','MNNIT']
  WHERE name = 'Motilal Nehru National Institute Of Technology' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['SVNIT Surat','SVNIT','NIT Surat']
  WHERE name = 'Sardar Vallabhbhai National Institute of Technology' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['VNIT Nagpur','VNIT','NIT Nagpur']
  WHERE name = 'Visvesvaraya National Institute of Technology' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NIT Kurukshetra','NITKKR']
  WHERE name = 'National Institute of Technology Kurukshetra' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NIT Durgapur','NITDGP']
  WHERE name = 'National Institute of Technology Durgapur' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NIT Silchar']
  WHERE name = 'National Institute of Technology Silchar' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NIT Srinagar']
  WHERE name = 'National Institute of Technology Srinagar' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NIT Raipur']
  WHERE name = 'National Institute of Technology Raipur' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NIT Jamshedpur']
  WHERE name = 'National Institute of Technology Jamshedpur' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NIT Goa']
  WHERE name = 'National Institute of Technology Goa' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NIT Patna']
  WHERE name = 'National Institute of Technology Patna' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['IIM Bangalore','IIMB']
  WHERE name = 'Indian Institute of Management Bangalore' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['IIM Trichy','IIM Tiruchirappalli']
  WHERE name = 'Indian Institute of Management, Tiruchirappalli' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['IIIT Bangalore','IIITB']
  WHERE name = 'International Institute of Information Technology, Bangalore' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['IIIT Allahabad','IIITA']
  WHERE name = 'Indian Institute of Information Technology Allahabad' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['JMI','Jamia']
  WHERE name = 'Jamia Millia Islamia' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['AMU']
  WHERE name = 'Aligarh Muslim University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['UoH','Hyderabad Central University','HCU']
  WHERE name = 'University of Hyderabad' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['DU','Delhi University']
  WHERE name = 'University of Delhi' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Mumbai University','MU']
  WHERE name = 'University of Mumbai' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Calcutta University']
  WHERE name = 'University of Calcutta' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Madras University']
  WHERE name = 'University of Madras' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['SPPU','Pune University','University of Pune']
  WHERE name = 'Savitribai Phule Pune University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['OU']
  WHERE name = 'Osmania University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['PU Chandigarh']
  WHERE name = 'Panjab University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Mysore University']
  WHERE name = 'University of Mysore' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Rajasthan University']
  WHERE name = 'University of Rajasthan' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['GGSIPU','IP University','IPU']
  WHERE name = 'Guru Gobind Singh Indraprastha University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Hamdard University']
  WHERE name = 'Jamia Hamdard' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Pondi University']
  WHERE name = 'Pondicherry University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['TISS']
  WHERE name = 'Tata Institute of Social Sciences' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['VIT','VIT Vellore']
  WHERE name = 'Vellore Institute of Technology' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['LPU']
  WHERE name = 'Lovely Professional University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Symbiosis','SIU']
  WHERE name = 'Symbiosis International University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Amrita University','Amrita']
  WHERE name = 'Amrita Vishwa Vidyapeetham' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['KIIT']
  WHERE name = 'Kalinga Institute of Industrial Technology' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Thapar University','TIET']
  WHERE name = 'Thapar Institute of Engineering and Technology' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Bennett']
  WHERE name = 'Bennett University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Shoolini']
  WHERE name = 'Shoolini University of Biotechnology and Management Sciences' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['NLSIU','NLS Bangalore']
  WHERE name = 'National Law School of India University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['ISI']
  WHERE name = 'Indian Statistical Institute' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['ISB','ISB Hyderabad']
  WHERE name = 'Indian School of Business Management and Administration' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['DSU','Dayananda Sagar']
  WHERE name = 'Dayananda Sagar University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['PESU']
  WHERE name = 'PES University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['JU']
  WHERE name = 'Jadavpur University' AND (aliases IS NULL OR cardinality(aliases) = 0);
UPDATE public.ref_universities SET aliases = ARRAY['Jain University','Jain']
  WHERE name = 'Jain (Deemed-to-be University)' AND (aliases IS NULL OR cardinality(aliases) = 0);
